// @ts-nocheck
/* GENERATED by scripts/generate-viewmodels.mjs from the legacy single-player
   viewmodel sources. Modeling is intentionally NOT re-authored. */
import * as THREE from 'three';

const MAXANISO = 8;
const PI = Math.PI;
const clamp = THREE.MathUtils.clamp;
const lerp = THREE.MathUtils.lerp;
const rand = (a, b) => a + Math.random() * (b - a);
const randI = (a, b) => Math.floor(rand(a, b + 1));
const pick = (a) => a[(Math.random() * a.length) | 0];
const damp = (cur, tgt, lambda, dt) => lerp(cur, tgt, 1 - Math.exp(-lambda * dt));
const easeOutCubic = (t) => 1 - (1 - t) ** 3;
const easeInOutCubic = (t) => (t < 0.5 ? 4 * t * t * t : 1 - (-2 * t + 2) ** 3 / 2);

function linearizeMats(dict) {
  for (const k in dict) {
    const m = dict[k];
    if (!m) continue;
    if (m.color && m.color.convertSRGBToLinear) m.color.convertSRGBToLinear();
    if (m.emissive && m.emissive.convertSRGBToLinear) m.emissive.convertSRGBToLinear();
  }
  return dict;
}

function cvs(size) {
  const c = document.createElement('canvas');
  c.width = c.height = size;
  return [c, c.getContext('2d')];
}

function finishTex(c, rep, srgb = true) {
  const t = new THREE.CanvasTexture(c);
  t.wrapS = t.wrapT = THREE.RepeatWrapping;
  if (rep) t.repeat.set(rep[0], rep[1]);
  t.anisotropy = MAXANISO;
  if (srgb) t.colorSpace = THREE.SRGBColorSpace;
  return t;
}

function grain(ctx, size, amt) {
  const img = ctx.getImageData(0, 0, size, size);
  const d = img.data;
  for (let i = 0; i < d.length; i += 4) {
    const n = (Math.random() - 0.5) * amt;
    d[i] = clamp(d[i] + n, 0, 255);
    d[i + 1] = clamp(d[i + 1] + n, 0, 255);
    d[i + 2] = clamp(d[i + 2] + n, 0, 255);
  }
  ctx.putImageData(img, 0, 0);
}

function splotches(ctx, size, n, colors, rMin, rMax, alpha) {
  for (let i = 0; i < n; i++) {
    const x = Math.random() * size;
    const y = Math.random() * size;
    const r = rand(rMin, rMax);
    const g = ctx.createRadialGradient(x, y, 0, x, y, r);
    const col = pick(colors);
    g.addColorStop(0, `rgba(${col},${alpha})`);
    g.addColorStop(1, `rgba(${col},0)`);
    ctx.fillStyle = g;
    ctx.beginPath();
    ctx.arc(x, y, r, 0, 7);
    ctx.fill();
  }
}

function makeGlowTex() {
  const S = 128;
  const [c, x] = cvs(S);
  const g = x.createRadialGradient(S / 2, S / 2, 0, S / 2, S / 2, S / 2);
  g.addColorStop(0, 'rgba(255,255,255,1)');
  g.addColorStop(0.22, 'rgba(255,236,180,.95)');
  g.addColorStop(0.5, 'rgba(255,150,40,.45)');
  g.addColorStop(1, 'rgba(255,90,0,0)');
  x.fillStyle = g;
  x.fillRect(0, 0, S, S);
  const t = new THREE.CanvasTexture(c);
  t.colorSpace = THREE.SRGBColorSpace;
  return t;
}

const TEX = { glow: makeGlowTex() };

/* The legacy prism scope samples the main render target. Campaign owns a
   different pipeline, so bridge it to a neutral texture; the exact world
   texture will be wired when the post chain is unified. */
const _bridgeCanvas = document.createElement('canvas');
_bridgeCanvas.width = _bridgeCanvas.height = 4;
const worldRT = { texture: new THREE.CanvasTexture(_bridgeCanvas) };
const RTW = window.innerWidth;
const RTH = window.innerHeight;
const allocTargets = { onPrismResize: [] };
const PRISM_MAGNIFICATION = 2.5;


/* ==== src/15-viewmodels.ts ==== */
/* =========================================================================
   8. VIEWMODELS — built from primitives, with gloved hands
   ========================================================================= */
/* Surface break-up for the gun. It fills a quarter of the screen at all times,
   so a flat albedo there is the most expensive flat albedo in the game: a
   little wear and roughness variation is what stops it reading as grey blocks. */
function makeWearTex(base, dark, light, speckle) {
  const S = 256,
    [c, x] = cvs(S);
  x.fillStyle = base;
  x.fillRect(0, 0, S, S);
  /* broad mottling so large flats aren't one value */
  for (let i = 0; i < 90; i++) {
    const cx = rand(0, S),
      cy = rand(0, S),
      r = rand(10, 54);
    const g = x.createRadialGradient(cx, cy, 0, cx, cy, r);
    g.addColorStop(0, Math.random() < 0.5 ? dark : light);
    g.addColorStop(1, 'rgba(0,0,0,0)');
    x.globalAlpha = rand(0.05, 0.16);
    x.fillStyle = g;
    x.beginPath();
    x.arc(cx, cy, r, 0, 7);
    x.fill();
  }
  /* micro scratches, mostly along the long axis of a machined part */
  x.globalAlpha = 1;
  for (let i = 0; i < 220; i++) {
    const x0 = rand(0, S),
      y0 = rand(0, S),
      len = rand(6, 70);
    x.strokeStyle = Math.random() < 0.55 ? 'rgba(255,255,255,0.055)' : 'rgba(0,0,0,0.085)';
    x.lineWidth = Math.random() < 0.85 ? 1 : 2;
    x.beginPath();
    x.moveTo(x0, y0);
    x.lineTo(x0 + len, y0 + rand(-2.5, 2.5));
    x.stroke();
  }
  /* edge-wear speckle: bare metal coming through the coating */
  if (speckle) {
    for (let i = 0; i < 170; i++) {
      x.fillStyle = 'rgba(255,255,255,' + rand(0.18, 0.46).toFixed(2) + ')';
      x.fillRect(rand(0, S), rand(0, S), rand(1, 3), rand(1, 2));
    }
  }
  grain(x, S, 11);
  return finishTex(c, [1, 1]);
}
/* Kept near white on purpose: this is a detail map that modulates the material
   colour, not the albedo itself. A mid-grey base would darken every tint by
   more than half. */
const TEX_GUNMETAL = makeWearTex('#e2e2e0', '#a6a6a4', '#ffffff', true);
const TEX_POLYMER = makeWearTex('#e0dfdc', '#a3a29e', '#ffffff', false);

/* Ripstop for the sleeves. A flat colour on a smooth cylinder is what makes an
   arm read as a plastic tube instead of a limb, so this leans on a visible weave
   plus soft blotching to break the silhouette up under any light. */
const TEX_SLEEVE = (() => {
  const S = 256,
    [c, x] = cvs(S);
  x.fillStyle = '#dedbd4';
  x.fillRect(0, 0, S, S);
  for (let i = 0; i < 70; i++) {
    const cx = rand(0, S),
      cy = rand(0, S),
      r = rand(14, 52);
    const g = x.createRadialGradient(cx, cy, 0, cx, cy, r);
    g.addColorStop(0, Math.random() < 0.5 ? '#9d9a92' : '#ffffff');
    g.addColorStop(1, 'rgba(0,0,0,0)');
    x.globalAlpha = rand(0.06, 0.2);
    x.fillStyle = g;
    x.beginPath();
    x.arc(cx, cy, r, 0, 7);
    x.fill();
  }
  x.globalAlpha = 1;
  x.strokeStyle = 'rgba(0,0,0,0.055)';
  x.lineWidth = 1;
  for (let i = 0; i < S; i += 6) {
    x.beginPath();
    x.moveTo(i, 0);
    x.lineTo(i, S);
    x.stroke();
    x.beginPath();
    x.moveTo(0, i);
    x.lineTo(S, i);
    x.stroke();
  }
  x.strokeStyle = 'rgba(255,255,255,0.05)';
  for (let i = 3; i < S; i += 6) {
    x.beginPath();
    x.moveTo(i, 0);
    x.lineTo(i, S);
    x.stroke();
  }
  grain(x, S, 9);
  return finishTex(c, [1, 1]);
})();

/* Same story as the soldier camo: primitive UVs run 0..1 regardless of size, so
   a shared map stretches wildly between a barrel and a stock. Run over the
   finished model once and rescale by actual dimensions instead of touching a
   hundred construction call sites. */
const GUN_PER_M = 5.5;
function texelize(root, perM) {
  root.traverse((o) => {
    const g = o.isMesh && o.material && o.material.map ? o.geometry : null;
    if (!g || !g.attributes.uv || g.userData.uvScaled) return;
    g.userData.uvScaled = true;
    const uv = g.attributes.uv;
    g.computeBoundingBox();
    const s = g.boundingBox.getSize(new THREE.Vector3());
    if (uv.count === 24) {
      // BoxGeometry: px nx py ny pz nz
      const face = [
        [s.z, s.y],
        [s.z, s.y],
        [s.x, s.z],
        [s.x, s.z],
        [s.x, s.y],
        [s.x, s.y],
      ];
      for (let f = 0; f < 6; f++) {
        const su = face[f][0] * perM,
          sv = face[f][1] * perM;
        for (let i = f * 4; i < f * 4 + 4; i++) uv.setXY(i, uv.getX(i) * su, uv.getY(i) * sv);
      }
    } else {
      // cylinders, spheres, cones
      const k = Math.max(s.x, s.y, s.z) * perM;
      for (let i = 0; i < uv.count; i++) uv.setXY(i, uv.getX(i) * k, uv.getY(i) * k);
    }
    uv.needsUpdate = true;
  });
}

/* the viewmodel sits against a bright outdoor scene, so the gun palette runs
   lighter than it looks on paper — anything darker reads as a black slab */
const GUNMETAL = new THREE.MeshStandardMaterial({
  map: TEX_GUNMETAL,
  color: 0x585855,
  metalness: 0.22,
  roughness: 0.46,
});
const POLYMER = new THREE.MeshStandardMaterial({
  map: TEX_POLYMER,
  color: 0x444340,
  metalness: 0.05,
  roughness: 0.76,
});
const POLYTAN = new THREE.MeshStandardMaterial({
  map: TEX_POLYMER,
  color: 0x685c47,
  metalness: 0.05,
  roughness: 0.78,
});
const STEEL = new THREE.MeshStandardMaterial({
  map: TEX_GUNMETAL,
  color: 0x9a9c9b,
  metalness: 0.28,
  roughness: 0.32,
});
const GLOVE = new THREE.MeshStandardMaterial({
  map: TEX_POLYMER,
  color: 0x474645,
  metalness: 0.04,
  roughness: 0.88,
});
const GLOVEPAD = new THREE.MeshStandardMaterial({
  color: 0x2b2b2a,
  metalness: 0.1,
  roughness: 0.6,
});
const SKIN = new THREE.MeshStandardMaterial({ color: 0xb08560, metalness: 0.0, roughness: 0.85 });
const SLEEVE = new THREE.MeshStandardMaterial({
  map: TEX_SLEEVE,
  color: 0x5d6350,
  metalness: 0.02,
  roughness: 0.92,
});
const SLEEVE_D = new THREE.MeshStandardMaterial({
  map: TEX_SLEEVE,
  color: 0x474c3d,
  metalness: 0.02,
  roughness: 0.94,
});
const ACCENT_R = new THREE.MeshStandardMaterial({
  color: 0xff2a1a,
  emissive: 0xff2a1a,
  emissiveIntensity: 1.4,
  roughness: 0.5,
});
/* Actual glass. This used to be an opaque disc, which put a dark plate across
   the sight line at exactly the moment you aimed at something — the target sat
   behind its own optic. Tinted and mostly clear reads like a coated lens, keeps
   enough cast for the dot to sit against, and lets you see what you are
   shooting. depthWrite off so it blends with the world instead of masking it. */
const OPTIC_GLASS = new THREE.MeshStandardMaterial({
  color: 0x9aa8ae,
  metalness: 0.08,
  roughness: 0.04,
  transparent: true,
  opacity: 0.045,
  depthWrite: false,
  side: THREE.DoubleSide,
});
/* optic bodies are open tubes, so their inner wall has to render too */
const TUBE_MAT = new THREE.MeshStandardMaterial({
  color: 0x33383e,
  metalness: 0.18,
  roughness: 0.55,
  side: THREE.DoubleSide,
});
linearizeMats({
  GUNMETAL,
  POLYMER,
  POLYTAN,
  STEEL,
  GLOVE,
  GLOVEPAD,
  SKIN,
  SLEEVE,
  ACCENT_R,
  OPTIC_GLASS,
  TUBE_MAT,
});

function part(parent, geo, mat, x, y, z, rx?, ry?, rz?, sx?, sy?, sz?) {
  const m = new THREE.Mesh(geo, mat);
  m.position.set(x || 0, y || 0, z || 0);
  m.rotation.set(rx || 0, ry || 0, rz || 0);
  if (sx !== undefined) m.scale.set(sx, sy === undefined ? sx : sy, sz === undefined ? sx : sz);
  parent.add(m);
  return m;
}
const B = (w, h, d) => new THREE.BoxGeometry(w, h, d);
const CYL = (r1, r2, h, s) => new THREE.CylinderGeometry(r1, r2, h, s || 10);
const CYLZ = (r1, r2, h, s) => {
  const g = CYL(r1, r2, h, s);
  g.rotateX(PI / 2);
  return g;
};
/** open-ended tube along Z — used for optics you have to see through */
const TUBEZ = (r, h, s) => {
  const g = new THREE.CylinderGeometry(r, r, h, s || 16, 1, true);
  g.rotateX(PI / 2);
  return g;
};

/** tactical glove — palm, fingers wrapped, thumb */
function makeHand(flip) {
  const g = new THREE.Group();
  const s = flip ? -1 : 1;
  part(g, B(0.072, 0.048, 0.1), GLOVE, 0, 0, 0);
  part(g, B(0.074, 0.024, 0.052), GLOVEPAD, 0, 0.014, -0.012);
  /* fingers curl forward+down around the grip */
  for (let i = 0; i < 4; i++) {
    const fg = new THREE.Group();
    fg.position.set(s * (0.026 - i * 0.0175), -0.016, 0.046);
    fg.rotation.x = -1.15 - i * 0.06;
    g.add(fg);
    part(fg, B(0.016, 0.014, 0.044), GLOVE, 0, 0, 0.02);
    const tip = new THREE.Group();
    tip.position.set(0, 0, 0.042);
    tip.rotation.x = -0.95;
    fg.add(tip);
    part(tip, B(0.016, 0.013, 0.034), GLOVE, 0, 0, 0.016);
  }
  /* thumb */
  const th = new THREE.Group();
  th.position.set(s * -0.032, 0.004, 0.024);
  th.rotation.set(-0.5, s * 0.55, 0);
  g.add(th);
  part(th, B(0.019, 0.018, 0.05), GLOVE, 0, 0, 0.024);
  /* wrist, then a forearm raked steeply down/back. It runs long on purpose:
     an arm that stops in mid-air makes the whole weapon read as a floating
     prop, so this one leaves the bottom of the frame instead of ending. */
  part(g, CYLZ(0.03, 0.034, 0.046, 10), GLOVEPAD, 0, 0, -0.052);
  const fore = new THREE.Group();
  fore.rotation.set(1.3, 0, s * 0.16);
  g.add(fore);
  /* Expose the long sleeve separately. During a reload the palm moves to the
     magazine, but dragging this entire first-person arm through the same grab
     point would put the sleeve in front of the camera. */
  g.forearm = fore;
  part(fore, CYLZ(0.04, 0.04, 0.022, 12), GLOVEPAD, 0, 0, 0.026); // glove cuff
  part(fore, CYLZ(0.038, 0.049, 0.2, 12), SLEEVE, 0, 0, 0.14); // forearm
  part(fore, CYLZ(0.049, 0.056, 0.3, 12), SLEEVE_D, 0, 0, 0.38); // upper sleeve, into frame edge
  /* elbow pad reads as kit rather than skin at the frame edge */
  part(fore, B(0.084, 0.03, 0.1), GLOVEPAD, 0, -0.03, 0.3);
  return g;
}

function buildMicroDot(parent, y, z) {
  const opt = new THREE.Group();
  opt.position.set(0, y, z);
  parent.add(opt);
  /* A raised skeleton mount, exposed adjustment turrets and a larger 24 mm
     window make this read as a modern duty optic instead of a black toy tube. */
  part(opt, B(0.064, 0.012, 0.086), GUNMETAL, 0, -0.021, 0);
  for (const x of [-0.024, 0.024]) part(opt, B(0.012, 0.034, 0.058), GUNMETAL, x, -0.003, 0);
  part(opt, B(0.043, 0.011, 0.064), POLYMER, 0, 0.017, 0);
  /* 30 mm clear window inside a visibly stout protective body. The cap rings
     deliberately overhang the tube, so their thickness is legible in ADS. */
  part(opt, TUBEZ(0.034, 0.086, 32), TUBE_MAT, 0, 0.05, 0);
  part(opt, TUBEZ(0.0395, 0.009, 32), GUNMETAL, 0, 0.05, -0.047);
  part(opt, TUBEZ(0.0395, 0.009, 32), GUNMETAL, 0, 0.05, 0.047);
  const glass = part(opt, CYLZ(0.0305, 0.0305, 0.0008, 32), OPTIC_GLASS, 0, 0.05, -0.038);
  glass.material = OPTIC_GLASS.clone();
  glass.material.opacity = 0.04;
  const rearGlass = part(opt, CYLZ(0.0305, 0.0305, 0.0008, 32), OPTIC_GLASS, 0, 0.05, 0.038);
  rearGlass.material = OPTIC_GLASS.clone();
  rearGlass.material.opacity = 0.03;
  /* Thin inner lip so the window reads as an opening, not a tinted disc. */
  part(opt, TUBEZ(0.0308, 0.0035, 28), GUNMETAL, 0, 0.05, -0.043);
  part(opt, B(0.02, 0.014, 0.024), POLYMER, 0, 0.093, 0.002);
  part(opt, CYLZ(0.011, 0.011, 0.014, 16), GUNMETAL, 0.043, 0.05, 0, 0, PI / 2, 0);
  part(opt, CYLZ(0.007, 0.007, 0.014, 12), GUNMETAL, -0.042, 0.05, 0.014, 0, PI / 2, 0);
  const dot = part(opt, new THREE.SphereGeometry(0.0017, 12, 10), ACCENT_R, 0, 0.05, -0.035);
  dot.material = ACCENT_R.clone();
  dot.material.emissiveIntensity = 3.4;
  dot.material.depthTest = false;
  dot.renderOrder = 20;
  const dotGlow = new THREE.Sprite(
    new THREE.SpriteMaterial({
      map: TEX.glow,
      color: 0xff2b18,
      transparent: true,
      blending: THREE.AdditiveBlending,
      depthTest: false,
      depthWrite: false,
      opacity: 0.62,
    })
  );
  dotGlow.scale.set(0.0068, 0.0068, 1);
  dotGlow.position.set(0, 0.05, -0.0345);
  dotGlow.renderOrder = 21;
  opt.add(dotGlow);
  /* User-facing red-dot option is intentionally chunky: the 1.3 scale is
     accounted for by the mount offsets, so the optical axis does not move. */
  opt.scale.setScalar(1.3);
  opt.userData.windowRadius = 0.031 * 1.3;
  opt.userData.frameRadius = 0.0395 * 1.3;
  opt.userData.aimY = 0.05;
  return { group: opt, dot, dotGlow, glass };
}

function buildRifle() {
  const G = new THREE.Group();
  /* upper receiver */
  part(G, B(0.076, 0.088, 0.3), GUNMETAL, 0, 0, -0.05);
  part(G, B(0.06, 0.028, 0.34), GUNMETAL, 0, 0.052, -0.06); // flat top
  /* picatinny teeth */
  for (let i = 0; i < 14; i++) part(G, B(0.052, 0.01, 0.01), POLYMER, 0, 0.07, -0.2 + i * 0.024);
  /* lower receiver + mag well */
  part(G, B(0.056, 0.072, 0.13), POLYMER, 0, -0.062, -0.06);
  const makeRifleMag = () => {
    const m = new THREE.Group();
    m.position.set(0, -0.135, -0.045);
    m.rotation.x = 0.18;
    G.add(m);
    part(m, B(0.048, 0.15, 0.082), POLYTAN, 0, 0, 0);
    part(m, B(0.052, 0.016, 0.086), POLYMER, 0, -0.08, 0);
    return m;
  };
  /* The old magazine and the incoming fresh one must coexist during the
     throw-and-catch overlap. Reusing one mesh made the old mag disappear and
     teleport back into the support hand. */
  const mag = makeRifleMag();
  const newMag = makeRifleMag();
  newMag.visible = false;
  const ejectedMag = makeRifleMag();
  ejectedMag.visible = false;
  /* handguard with vents */
  part(G, B(0.07, 0.074, 0.26), POLYMER, 0, -0.004, -0.3);
  for (let i = 0; i < 5; i++) {
    part(G, B(0.074, 0.016, 0.02), GUNMETAL, 0, -0.024, -0.4 + i * 0.045);
  }
  part(G, B(0.05, 0.014, 0.24), POLYMER, 0, 0.048, -0.3);
  /* barrel + flash hider */
  part(G, CYLZ(0.0165, 0.0165, 0.34, 10), STEEL, 0, 0.006, -0.5);
  const compensator = new THREE.Group();
  G.add(compensator);
  part(compensator, CYLZ(0.024, 0.021, 0.062, 10), GUNMETAL, 0, 0.006, -0.685);
  for (let i = 0; i < 3; i++)
    part(compensator, B(0.052, 0.006, 0.018), GUNMETAL, 0, 0.006, -0.672 + i * 0.02);
  part(compensator, CYLZ(0.02, 0.02, 0.014, 10), POLYMER, 0, 0.006, -0.716); // bore
  const suppressor = new THREE.Group();
  suppressor.visible = false;
  G.add(suppressor);
  part(suppressor, CYLZ(0.032, 0.029, 0.25, 16), GUNMETAL, 0, 0.006, -0.79);
  /* gas block + front sight */
  part(G, B(0.04, 0.052, 0.05), GUNMETAL, 0, 0.02, -0.44);
  part(G, B(0.014, 0.052, 0.012), GUNMETAL, 0, 0.062, -0.44);
  const optic = buildMicroDot(G, 0.054, -0.1);
  const prism = buildPrismScope(G, 0.119, -0.1);
  const holo = buildHoloSight(G, 0.104, -0.1);
  prism.group.visible = false;
  holo.group.visible = false;
  const angledGrip = new THREE.Group(),
    verticalGrip = new THREE.Group();
  verticalGrip.visible = false;
  G.add(angledGrip, verticalGrip);
  part(angledGrip, B(0.05, 0.045, 0.13), POLYMER, 0, -0.065, -0.33, -0.2, 0, 0);
  part(verticalGrip, B(0.042, 0.14, 0.055), POLYMER, 0, -0.12, -0.33, -0.1, 0, 0);
  /* charging handle + ejection port + brass deflector */
  part(G, B(0.03, 0.014, 0.05), GUNMETAL, 0, 0.038, 0.1);
  part(G, B(0.01, 0.03, 0.075), GUNMETAL, 0.04, 0.014, -0.045);
  part(G, B(0.016, 0.034, 0.03), GUNMETAL, 0.042, 0.03, 0.03);
  /* forward assist */
  part(G, CYLZ(0.011, 0.011, 0.03, 8), GUNMETAL, -0.042, 0.008, 0.03);
  /* pistol grip */
  const grip = new THREE.Group();
  grip.position.set(0, -0.086, 0.048);
  grip.rotation.x = -0.3;
  G.add(grip);
  part(grip, B(0.048, 0.125, 0.062), POLYMER, 0, -0.055, 0);
  part(grip, B(0.05, 0.03, 0.066), GLOVEPAD, 0, -0.108, 0);
  /* trigger + guard */
  part(G, B(0.014, 0.03, 0.01), STEEL, 0, -0.052, -0.015);
  part(G, B(0.048, 0.01, 0.056), POLYMER, 0, -0.072, -0.02);
  part(G, B(0.048, 0.036, 0.01), POLYMER, 0, -0.056, -0.046);
  /* stock */
  part(G, CYLZ(0.021, 0.021, 0.14, 10), GUNMETAL, 0, -0.006, 0.18);
  const st = new THREE.Group();
  st.position.set(0, -0.01, 0.235);
  G.add(st);
  part(st, B(0.062, 0.088, 0.13), POLYMER, 0, 0, 0);
  part(st, B(0.066, 0.104, 0.024), GLOVEPAD, 0, -0.006, 0.072);
  part(st, B(0.048, 0.03, 0.1), POLYMER, 0, 0.052, -0.01);
  /* sling swivel */
  part(G, B(0.008, 0.026, 0.008), STEEL, 0.036, -0.036, 0.16);

  const muzzle = new THREE.Object3D();
  muzzle.position.set(0, 0.006, -0.73);
  G.add(muzzle);
  const eject = new THREE.Object3D();
  eject.position.set(0.055, 0.02, -0.03);
  G.add(eject);
  const reloadSlap = new THREE.Object3D();
  reloadSlap.position.set(-0.052, -0.025, -0.015);
  G.add(reloadSlap);
  const rightGrip = new THREE.Object3D();
  rightGrip.position.set(0.008, -0.14, 0.075);
  G.add(rightGrip);

  const hands = new THREE.Group();
  G.add(hands);
  const rh = makeHand(false);
  rh.position.set(0.008, -0.14, 0.075);
  rh.rotation.set(0.3, 0, 0.1);
  hands.add(rh);
  const lh = makeHand(true);
  lh.position.set(-0.01, -0.072, -0.315);
  lh.rotation.set(0.05, 0.0, -0.18);
  hands.add(lh);

  /* Weapon geometry and hands need different animation spaces. A reload may
     roll the receiver almost ninety degrees, while wrists and forearms only
     follow the controls with a much smaller anatomical turn. */
  const weaponPivot = new THREE.Group();
  for (const child of [...G.children]) {
    if (child !== hands && child !== ejectedMag) weaponPivot.add(child);
  }
  G.add(weaponPivot);

  return {
    group: G,
    weaponPivot,
    muzzle,
    eject,
    dot: optic.dot,
    dotGlow: optic.dotGlow,
    opticGlass: optic.glass,
    prism,
    holo,
    attachmentNodes: {
      optic: { micro_dot: optic.group, holo: holo.group, prism_2_5: prism.group },
      muzzle: { compensator, suppressor },
      underbarrel: { angled_grip: angledGrip, vertical_grip: verticalGrip },
    },
    mag,
    newMag,
    ejectedMag,
    reloadSlap,
    rightGrip,
    hands,
    leftHand: lh,
    rightHand: rh,
    /* held low and canted, so the buttstock falls past the bottom of the
              frame the way it does over a real shoulder instead of parking a
              slab of polymer in the middle of the screen */
    basePos: new THREE.Vector3(0.205, -0.243, -0.928),
    baseRot: new THREE.Vector3(-0.028, 0.082, 0.055),
    /* ADS poses put the sight on the vm camera's -Z axis: x=0 and
              y = -(sight height in model space), neither of which depends on how
              far out the weapon sits. adsRef is how far that sight ends up from
              the eye, which is what the dolly compensates for. */
    adsPos: new THREE.Vector3(0.0006, -0.118, -0.866),
    adsRot: new THREE.Vector3(0, 0, 0),
    adsRef: 0.986,
  };
}

function buildShotgun() {
  const G = new THREE.Group();
  /* receiver */
  part(G, B(0.082, 0.098, 0.26), GUNMETAL, 0, 0, -0.02);
  part(G, B(0.086, 0.02, 0.2), POLYMER, 0, 0.052, -0.03);
  part(G, B(0.014, 0.04, 0.075), GUNMETAL, 0.044, 0.006, -0.03); // ejection port
  /* barrel + heat shield */
  part(G, CYLZ(0.0235, 0.0235, 0.6, 12), GUNMETAL, 0, 0.02, -0.44);
  for (let i = 0; i < 7; i++) part(G, B(0.056, 0.01, 0.014), STEEL, 0, 0.05, -0.3 - i * 0.055);
  part(G, B(0.01, 0.016, 0.3), STEEL, 0.03, 0.038, -0.42);
  part(G, B(0.01, 0.016, 0.3), STEEL, -0.03, 0.038, -0.42);
  part(G, CYLZ(0.028, 0.026, 0.05, 12), GUNMETAL, 0, 0.02, -0.735);
  part(G, CYLZ(0.021, 0.021, 0.012, 12), POLYMER, 0, 0.02, -0.756);
  /* front bead, raised on a post so the sight line clears the heat shield */
  part(G, B(0.008, 0.02, 0.01), STEEL, 0, 0.052, -0.72);
  part(G, new THREE.SphereGeometry(0.0065, 8, 6), ACCENT_R, 0, 0.065, -0.72);
  /* tube magazine */
  part(G, CYLZ(0.0195, 0.0195, 0.52, 10), GUNMETAL, 0, -0.03, -0.4);
  part(G, CYLZ(0.022, 0.022, 0.03, 10), STEEL, 0, -0.03, -0.665);
  part(G, B(0.012, 0.03, 0.014), STEEL, 0, -0.052, -0.34);
  /* pump forend (animated) */
  const forend = new THREE.Group();
  forend.position.set(0, -0.014, -0.34);
  G.add(forend);
  part(forend, B(0.078, 0.07, 0.185), POLYMER, 0, 0, 0);
  for (let i = 0; i < 6; i++)
    part(forend, B(0.082, 0.011, 0.013), GLOVEPAD, 0, -0.016, -0.07 + i * 0.028);
  part(forend, B(0.07, 0.02, 0.19), POLYMER, 0, 0.034, 0);
  /* stock */
  const st = new THREE.Group();
  st.position.set(0, -0.028, 0.19);
  st.rotation.x = 0.1;
  G.add(st);
  part(st, B(0.066, 0.1, 0.2), POLYMER, 0, -0.008, 0.06);
  part(st, B(0.07, 0.118, 0.026), GLOVEPAD, 0, -0.02, 0.164);
  part(st, B(0.05, 0.036, 0.14), POLYMER, 0, 0.056, 0.03);
  /* grip area */
  const grip = new THREE.Group();
  grip.position.set(0, -0.062, 0.075);
  grip.rotation.x = -0.38;
  G.add(grip);
  part(grip, B(0.05, 0.115, 0.062), POLYMER, 0, -0.052, 0);
  part(G, B(0.014, 0.028, 0.01), STEEL, 0, -0.048, -0.012);
  part(G, B(0.046, 0.01, 0.056), GUNMETAL, 0, -0.068, -0.016);
  /* shell carrier hint */
  part(G, B(0.052, 0.014, 0.08), GLOVEPAD, 0, -0.052, -0.06);
  /* One visible shell sells the loading-port action. It is hidden outside a
     reload and animated by the shared viewmodel rig. */
  const reloadShell = new THREE.Group();
  reloadShell.position.set(-0.015, -0.075, -0.075);
  reloadShell.visible = false;
  G.add(reloadShell);
  part(reloadShell, CYLZ(0.012, 0.012, 0.06, 10), ACCENT_R, 0, 0, 0);
  part(reloadShell, CYLZ(0.013, 0.013, 0.009, 10), STEEL, 0, 0, 0.034);

  const muzzle = new THREE.Object3D();
  muzzle.position.set(0, 0.02, -0.77);
  G.add(muzzle);
  const eject = new THREE.Object3D();
  eject.position.set(0.06, 0.01, -0.02);
  G.add(eject);

  const hands = new THREE.Group();
  G.add(hands);
  const rh = makeHand(false);
  rh.position.set(0.006, -0.118, 0.1);
  rh.rotation.set(0.38, 0, 0.1);
  hands.add(rh);
  const lh = makeHand(true);
  lh.rotation.set(0.06, 0, -0.15);
  forend.add(lh);
  lh.position.set(-0.006, -0.064, -0.005); // rides the pump

  return {
    group: G,
    muzzle,
    eject,
    forend,
    reloadShell,
    hands,
    leftHand: lh,
    basePos: new THREE.Vector3(0.222, -0.255, -0.986),
    baseRot: new THREE.Vector3(-0.023, 0.086, 0.055),
    adsPos: new THREE.Vector3(0.0006, -0.065, -1.033),
    adsRot: new THREE.Vector3(0, 0, 0),
    adsRef: 1.653,
  }; // front bead
}


/* ==== src/15a-optics-prism.ts ==== */
function buildPrismScope(parent, sightY, z) {
  const scope = new THREE.Group();
  scope.position.set(0, sightY, z);
  parent.add(scope);
  /* Wide cantilever base, reinforced body and rubberized ocular ring. */
  /* Keep every support below the ocular cone. The previous twin uprights rose
     into the lower half of the lens when the eye moved close in ADS. */
  part(scope, B(0.078, 0.012, 0.15), GUNMETAL, 0, -0.061, 0.018);
  const mount = new THREE.Group();
  mount.position.set(0, -0.048, 0.018);
  scope.add(mount);
  for (const x of [-0.031, 0.031])
    part(mount, B(0.011, 0.026, 0.09), GUNMETAL, x, 0, 0, -0.12, 0, 0);
  part(mount, B(0.068, 0.012, 0.085), GUNMETAL, 0, -0.014, 0);
  /* CylinderGeometry is capped by default, which put an opaque metal disc
     directly across the sight picture once the optic moved close to the eye.
     The body must be an open, double-sided tube; the rings below provide the
     visible wall thickness without ever covering the optical path. */
  part(scope, TUBEZ(0.043, 0.18, 32), TUBE_MAT, 0, 0, 0);
  part(scope, TUBEZ(0.048, 0.018, 32), GUNMETAL, 0, 0, 0.098);
  part(scope, TUBEZ(0.047, 0.016, 32), GUNMETAL, 0, 0, -0.098);
  part(scope, TUBEZ(0.041, 0.022, 32), GLOVEPAD, 0, 0, 0.107);
  /* Turrets and illumination dial keep the silhouette distinct from the dot. */
  part(scope, CYL(0.013, 0.013, 0.018, 16), GUNMETAL, 0, 0.047, -0.012);
  part(scope, CYLZ(0.013, 0.013, 0.018, 16), GUNMETAL, 0.05, 0, -0.012, 0, PI / 2, 0);
  /* Sample the world-only frame at the lens's screen coordinates. This is not
     another camera or another zoom: it simply prevents viewmodel rail/mount
     geometry behind the transparent lens from leaking into the aperture. */
  const lensMat = new THREE.ShaderMaterial({
    uniforms: {
      tWorld: { value: worldRT.texture },
      resolution: { value: new THREE.Vector2(RTW, RTH) },
    },
    vertexShader: `void main(){ gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.0); }`,
    fragmentShader: `
      uniform sampler2D tWorld;
      uniform vec2 resolution;
      void main(){
        vec2 uv=gl_FragCoord.xy/resolution;
        vec3 world=texture2D(tWorld,uv).rgb;
        gl_FragColor=vec4(world*vec3(.94,1.01,1.04),1.0);
      }`,
    depthTest: true,
    depthWrite: true,
    transparent: false,
    toneMapped: false,
  });
  /* Slightly overlap the tube's inner radius so no sub-pixel annulus can leak
     viewmodel geometry around the world-only aperture. The metal ocular ring
     renders in front and hides the overlap. */
  const lens = part(scope, new THREE.CircleGeometry(0.0425, 48), lensMat, 0, 0, 0.102);
  lens.renderOrder = 16;
  const glassMat = OPTIC_GLASS.clone();
  glassMat.opacity = 0.09;
  glassMat.depthWrite = false;
  part(scope, new THREE.CircleGeometry(0.042, 48), glassMat, 0, 0, 0.103);
  /* Draw a front-facing ocular bezel after the sampled world so the metal
     frame cannot disappear into a similarly dark background. */
  const bezelMat = new THREE.MeshBasicMaterial({
    color: 0x090c0f,
    depthTest: false,
    depthWrite: false,
    side: THREE.DoubleSide,
  });
  const bezel = part(scope, new THREE.RingGeometry(0.0415, 0.052, 48), bezelMat, 0, 0, 0.104);
  bezel.renderOrder = 24;
  /* Etched illuminated cross: visible over the magnified world, but fine
     enough not to conceal a distant head. */
  const reticleMat = new THREE.MeshBasicMaterial({
    color: 0xff442e,
    transparent: true,
    opacity: 0.42,
    depthTest: false,
    depthWrite: false,
  });
  const h = part(scope, B(0.012, 0.0007, 0.0005), reticleMat, 0, 0, 0.105);
  const v = part(scope, B(0.0007, 0.012, 0.0005), reticleMat, 0, 0, 0.105);
  h.renderOrder = v.renderOrder = 25;
  scope.scale.setScalar(1.45);
  scope.userData.mount = mount;
  scope.userData.aimY = 0;
  scope.userData.clearApertureRadius = 0.042;
  scope.userData.magnification = PRISM_MAGNIFICATION;
  scope.userData.bezel = bezel;
  scope.userData.reticle = { h, v };
  (allocTargets as any).onPrismResize ||= [];
  (allocTargets as any).onPrismResize.push(() => {
    lensMat.uniforms.tWorld.value = worldRT.texture;
    lensMat.uniforms.resolution.value.set(RTW, RTH);
  });
  return { group: scope, lens, lensMat };
}


/* ==== src/15b-optics-holo.ts ==== */
/* A 1x holographic sight has a broad, rectangular viewing window rather than
   the circular tube silhouette used by the red dot and prism. The reticle is
   rendered independently of depth so it reads as a collimated projection. */
function buildHoloSight(parent, sightY, z) {
  const sight = new THREE.Group();
  sight.position.set(0, sightY, z);
  parent.add(sight);

  /* Picatinny clamp and raised bridge. */
  part(sight, B(0.108, 0.014, 0.112), GUNMETAL, 0, -0.063, 0.008);
  for (const x of [-0.036, 0.036]) part(sight, B(0.016, 0.028, 0.076), GUNMETAL, x, -0.047, 0.004);
  part(sight, B(0.094, 0.014, 0.082), POLYMER, 0, -0.034, 0);

  /* Thick square hood. Keeping the four sides as separate solids leaves a
     genuinely open aperture instead of hiding a capped primitive in it. */
  part(sight, B(0.112, 0.017, 0.086), GLOVEPAD, 0, 0.052, 0);
  part(sight, B(0.112, 0.017, 0.086), GUNMETAL, 0, -0.032, 0);
  for (const x of [-0.048, 0.048]) part(sight, B(0.017, 0.09, 0.086), GUNMETAL, x, 0.01, 0);
  /* Front bevel and adjustment controls make the housing readable at hip. */
  part(sight, B(0.102, 0.006, 0.092), GUNMETAL, 0, 0.047, -0.004);
  part(sight, B(0.006, 0.078, 0.092), GUNMETAL, -0.043, 0.01, -0.004);
  part(sight, B(0.006, 0.078, 0.092), GUNMETAL, 0.043, 0.01, -0.004);
  part(sight, CYLZ(0.01, 0.01, 0.016, 14), GUNMETAL, 0.058, 0.006, 0.012, 0, PI / 2, 0);

  const glassMat = OPTIC_GLASS.clone();
  glassMat.color.setHex(0x527f8b);
  glassMat.emissive.setHex(0x0b2025);
  glassMat.opacity = 0.11;
  glassMat.depthWrite = false;
  glassMat.side = THREE.DoubleSide;
  const glass = part(sight, new THREE.PlaneGeometry(0.078, 0.064), glassMat, 0, 0.01, -0.038);
  glass.renderOrder = 10;

  const reticleMat = new THREE.MeshBasicMaterial({
    color: 0xff3b24,
    transparent: true,
    opacity: 0.58,
    depthTest: false,
    depthWrite: false,
    side: THREE.DoubleSide,
  });
  const ring = part(sight, new THREE.RingGeometry(0.0085, 0.0096, 32), reticleMat, 0, 0.01, -0.04);
  const dot = part(sight, new THREE.CircleGeometry(0.00145, 16), reticleMat, 0, 0.01, -0.0402);
  ring.renderOrder = dot.renderOrder = 22;
  sight.userData.kind = 'holographic';
  sight.userData.aimY = 0.01;
  sight.userData.window = { width: 0.078, height: 0.064 };
  sight.userData.reticle = { ring, dot };
  return { group: sight, glass, ring, dot };
}


/* ==== src/16-viewmodels-b.ts ==== */
function makeReloadMagazineSet(mag, root) {
  const newMag = mag.clone(true),
    ejectedMag = mag.clone(true);
  newMag.visible = false;
  ejectedMag.visible = false;
  mag.parent.add(newMag);
  root.add(ejectedMag);
  return { newMag, ejectedMag };
}

function buildPistol() {
  const G = new THREE.Group();
  /* slide */
  const slide = new THREE.Group();
  G.add(slide);
  part(slide, B(0.046, 0.054, 0.215), GUNMETAL, 0, 0.012, -0.055);
  part(slide, B(0.048, 0.014, 0.215), POLYMER, 0, 0.036, -0.055);
  for (let i = 0; i < 7; i++)
    part(slide, B(0.049, 0.03, 0.007), GLOVEPAD, 0, 0.01, 0.01 + i * 0.014);
  part(slide, B(0.009, 0.013, 0.01), STEEL, 0, 0.045, -0.15); // front post
  part(slide, B(0.006, 0.008, 0.011), ACCENT_R, 0, 0.047, -0.15); // front bead
  /* rear sight is split so the notch actually shows the target */
  part(slide, B(0.01, 0.013, 0.012), STEEL, -0.01, 0.045, 0.036);
  part(slide, B(0.01, 0.013, 0.012), STEEL, 0.01, 0.045, 0.036);
  part(slide, B(0.005, 0.006, 0.013), ACCENT_R, -0.011, 0.046, 0.036);
  part(slide, B(0.005, 0.006, 0.013), ACCENT_R, 0.011, 0.046, 0.036);
  part(slide, B(0.014, 0.03, 0.062), GUNMETAL, 0.026, 0.014, -0.03); // ejection port
  part(slide, CYLZ(0.0135, 0.0135, 0.03, 10), STEEL, 0, 0.008, -0.16);
  part(slide, CYLZ(0.01, 0.01, 0.012, 10), POLYMER, 0, 0.008, -0.17);
  /* frame */
  part(G, B(0.04, 0.032, 0.185), POLYMER, 0, -0.024, -0.045);
  part(G, B(0.044, 0.012, 0.1), POLYMER, 0, -0.04, -0.1); // accessory rail
  for (let i = 0; i < 3; i++) part(G, B(0.046, 0.014, 0.01), GLOVEPAD, 0, -0.04, -0.07 - i * 0.024);
  /* grip + magwell */
  const grip = new THREE.Group();
  grip.position.set(0, -0.04, 0.03);
  grip.rotation.x = -0.28;
  G.add(grip);
  part(grip, B(0.042, 0.135, 0.058), POLYMER, 0, -0.066, 0);
  for (let i = 0; i < 5; i++)
    part(grip, B(0.044, 0.009, 0.062), GLOVEPAD, 0, -0.028 - i * 0.021, 0);
  const mag = new THREE.Group();
  mag.position.set(0, -0.136, 0);
  grip.add(mag);
  part(mag, B(0.034, 0.11, 0.045), GUNMETAL, 0, 0.055, 0);
  part(mag, B(0.046, 0.014, 0.062), GUNMETAL, 0, 0, 0);
  const pistolMags = makeReloadMagazineSet(mag, G);
  /* trigger guard */
  part(G, B(0.04, 0.009, 0.052), POLYMER, 0, -0.056, -0.018);
  part(G, B(0.04, 0.03, 0.009), POLYMER, 0, -0.043, -0.041);
  part(G, B(0.011, 0.026, 0.009), STEEL, 0, -0.038, -0.014);
  /* hammer / beavertail */
  part(G, B(0.02, 0.02, 0.026), GUNMETAL, 0, 0.006, 0.062);
  part(G, B(0.034, 0.01, 0.04), POLYMER, 0, -0.01, 0.058);

  const suppressor = new THREE.Group();
  suppressor.visible = false;
  G.add(suppressor);
  part(suppressor, CYLZ(0.016, 0.0148, 0.092, 12), GUNMETAL, 0, 0.008, -0.238);
  part(suppressor, TUBEZ(0.0164, 0.01, 12), POLYMER, 0, 0.008, -0.21);
  const muzzle = new THREE.Object3D();
  muzzle.position.set(0, 0.008, -0.185);
  G.add(muzzle);
  const eject = new THREE.Object3D();
  eject.position.set(0.04, 0.02, -0.03);
  G.add(eject);

  const hands = new THREE.Group();
  G.add(hands);
  const rh = makeHand(false);
  rh.position.set(0.01, -0.108, 0.052);
  rh.rotation.set(0.28, 0, 0.12);
  hands.add(rh);
  const lh = makeHand(true);
  lh.position.set(-0.046, -0.1, 0.036);
  lh.rotation.set(0.34, 0.22, -0.3);
  hands.add(lh);

  return {
    group: G,
    muzzle,
    eject,
    slide,
    mag,
    ...pistolMags,
    hands,
    leftHand: lh,
    rightHand: rh,
    basePos: new THREE.Vector3(0.175, -0.232, -0.754),
    baseRot: new THREE.Vector3(-0.022, 0.072, 0.05),
    adsPos: new THREE.Vector3(0.0006, -0.0448, -0.4935),
    adsRot: new THREE.Vector3(0, 0, 0),
    adsRef: 0.6235,
    attachmentNodes: { muzzle: { suppressor } },
  }; // front post
}

function buildSniper() {
  const G = new THREE.Group();
  /* receiver + rail */
  part(G, B(0.07, 0.082, 0.4), GUNMETAL, 0, 0, -0.02);
  part(G, B(0.056, 0.022, 0.44), GUNMETAL, 0, 0.05, -0.03);
  for (let i = 0; i < 16; i++) part(G, B(0.048, 0.009, 0.01), POLYMER, 0, 0.064, -0.22 + i * 0.026);
  /* fluted heavy barrel + brake */
  part(G, CYLZ(0.0215, 0.0195, 0.62, 12), STEEL, 0, 0.004, -0.55);
  for (let i = 0; i < 8; i++) part(G, B(0.046, 0.007, 0.03), GUNMETAL, 0, 0.004, -0.34 - i * 0.062);
  part(G, CYLZ(0.03, 0.028, 0.09, 12), GUNMETAL, 0, 0.004, -0.9);
  for (let i = 0; i < 4; i++)
    part(G, B(0.064, 0.008, 0.012), GUNMETAL, 0, 0.004, -0.875 - i * 0.02);
  part(G, CYLZ(0.023, 0.023, 0.014, 12), POLYMER, 0, 0.004, -0.946); // bore
  /* chassis fore-end with M-LOK slots */
  part(G, B(0.076, 0.062, 0.34), POLYTAN, 0, -0.02, -0.36);
  for (let i = 0; i < 5; i++) part(G, B(0.08, 0.014, 0.024), POLYMER, 0, -0.03, -0.48 + i * 0.058);
  part(G, B(0.05, 0.014, 0.3), POLYTAN, 0, 0.014, -0.36);
  /* folded bipod tucked under the fore-end */
  const bp = new THREE.Group();
  bp.position.set(0, -0.056, -0.47);
  G.add(bp);
  part(bp, B(0.026, 0.02, 0.07), GUNMETAL, 0, 0, 0);
  part(bp, CYLZ(0.0075, 0.0075, 0.17, 8), STEEL, -0.02, -0.01, 0.055, 0.3, 0, 0);
  part(bp, CYLZ(0.0075, 0.0075, 0.17, 8), STEEL, 0.02, -0.01, 0.055, 0.3, 0, 0);
  /* scope: tube, bells, turrets, rings */
  const sc = new THREE.Group();
  sc.position.set(0, 0.118, -0.1);
  G.add(sc);
  part(sc, CYLZ(0.0225, 0.0225, 0.3, 16), GUNMETAL, 0, 0, 0);
  part(sc, CYLZ(0.0335, 0.0335, 0.075, 16), GUNMETAL, 0, 0, -0.185); // objective bell
  part(sc, CYLZ(0.029, 0.029, 0.06, 16), GUNMETAL, 0, 0, 0.17); // ocular bell
  part(sc, CYLZ(0.03, 0.03, 0.008, 16), OPTIC_GLASS, 0, 0, -0.221);
  part(sc, CYLZ(0.0255, 0.0255, 0.008, 16), OPTIC_GLASS, 0, 0, 0.199);
  part(sc, CYL(0.017, 0.017, 0.03, 12), GUNMETAL, 0, 0.03, -0.02); // elevation turret
  part(sc, B(0.03, 0.006, 0.03), POLYMER, 0, 0.046, -0.02);
  part(sc, CYLZ(0.016, 0.016, 0.03, 12), GUNMETAL, 0.03, 0, -0.02, 0, PI / 2, 0); // windage turret
  part(sc, CYLZ(0.0155, 0.0155, 0.028, 12), GUNMETAL, 0, 0, 0.075); // magnification ring
  for (let i = 0; i < 8; i++)
    part(sc, B(0.005, 0.034, 0.026), POLYMER, 0, 0, 0.075, 0, 0, (i * PI) / 4);
  part(G, B(0.036, 0.052, 0.03), GUNMETAL, 0, 0.086, -0.2); // rings
  part(G, B(0.036, 0.052, 0.03), GUNMETAL, 0, 0.086, 0.0);
  /* bolt assembly — pulls back and rotates up during the cycle */
  const bolt = new THREE.Group();
  bolt.position.set(0.038, 0.026, 0.1);
  G.add(bolt);
  part(bolt, CYLZ(0.012, 0.012, 0.11, 10), STEEL, 0, 0, 0);
  const knob = new THREE.Group();
  knob.position.set(0, 0, 0.05);
  bolt.add(knob);
  part(knob, CYLZ(0.0095, 0.0095, 0.062, 8), STEEL, 0.026, 0, 0, 0, PI / 2, 0);
  part(knob, new THREE.SphereGeometry(0.0185, 10, 8), GUNMETAL, 0.058, 0, 0);
  /* detachable box mag */
  const mag = new THREE.Group();
  mag.position.set(0, -0.098, -0.055);
  G.add(mag);
  part(mag, B(0.044, 0.11, 0.095), POLYMER, 0, 0, 0);
  part(mag, B(0.048, 0.014, 0.099), GLOVEPAD, 0, -0.058, 0);
  const sniperMags = makeReloadMagazineSet(mag, G);
  /* trigger group + guard */
  part(G, B(0.013, 0.03, 0.01), STEEL, 0, -0.052, 0.02);
  part(G, B(0.046, 0.01, 0.062), POLYMER, 0, -0.07, 0.014);
  part(G, B(0.046, 0.032, 0.01), POLYMER, 0, -0.056, -0.014);
  /* thumbhole grip */
  const grip = new THREE.Group();
  grip.position.set(0, -0.08, 0.105);
  grip.rotation.x = -0.22;
  G.add(grip);
  part(grip, B(0.046, 0.13, 0.06), POLYTAN, 0, -0.058, 0);
  part(grip, B(0.048, 0.03, 0.064), GLOVEPAD, 0, -0.112, 0);
  /* skeleton stock with adjustable cheek riser */
  const st = new THREE.Group();
  st.position.set(0, -0.006, 0.235);
  G.add(st);
  part(st, B(0.058, 0.07, 0.1), POLYTAN, 0, 0, 0);
  part(st, B(0.05, 0.028, 0.15), POLYTAN, 0, 0.052, 0.075); // cheek riser
  part(st, CYLZ(0.008, 0.008, 0.05, 8), STEEL, -0.018, 0.026, 0.075, 1.57, 0, 0);
  part(st, CYLZ(0.008, 0.008, 0.05, 8), STEEL, 0.018, 0.026, 0.075, 1.57, 0, 0);
  part(st, B(0.052, 0.02, 0.16), POLYTAN, 0, -0.028, 0.08);
  part(st, B(0.058, 0.11, 0.026), GLOVEPAD, 0, 0.006, 0.168); // butt pad
  part(st, B(0.03, 0.04, 0.05), GUNMETAL, 0, -0.052, 0.15); // monopod spur

  const muzzle = new THREE.Object3D();
  muzzle.position.set(0, 0.004, -0.96);
  G.add(muzzle);
  const eject = new THREE.Object3D();
  eject.position.set(0.055, 0.02, 0.06);
  G.add(eject);
  const rightGrip = new THREE.Object3D();
  rightGrip.position.set(0.01, -0.136, 0.128);
  G.add(rightGrip);

  const hands = new THREE.Group();
  G.add(hands);
  const rh = makeHand(false);
  rh.position.set(0.01, -0.136, 0.128);
  rh.rotation.set(0.26, 0, 0.1);
  hands.add(rh);
  const lh = makeHand(true);
  lh.position.set(-0.012, -0.078, -0.38);
  lh.rotation.set(0.04, 0, -0.16);
  hands.add(lh);

  /* Roll the weapon independently. Neither shoulder inherits this turn. */
  const weaponPivot = new THREE.Group();
  for (const child of [...G.children]) {
    /* Both loose magazines live in the same upright space as the hands. The
       seated mag remains on the rifle, but rolling the receiver must not roll
       a magazine that has already been pulled free or fetched from a pouch. */
    if (child !== hands && child !== sniperMags.ejectedMag && child !== sniperMags.newMag)
      weaponPivot.add(child);
  }
  G.add(weaponPivot);

  return {
    group: G,
    weaponPivot,
    muzzle,
    eject,
    bolt,
    knob,
    mag,
    ...sniperMags,
    rightGrip,
    hands,
    leftHand: lh,
    rightHand: rh,
    basePos: new THREE.Vector3(0.224, -0.262, -1.16),
    baseRot: new THREE.Vector3(-0.022, 0.084, 0.055),
    /* the scope tube sits at y 0.118, so the eye line drops by that much */
    adsPos: new THREE.Vector3(0.0006, -0.1185, -0.6205),
    adsRot: new THREE.Vector3(0, 0, 0),
    adsRef: 0.7105,
  }; // scope centre
}

/* SAW-250: a belt-fed brick. Boxy receiver, ammo can hanging off the left,
   heat-shielded barrel, folded bipod, aperture rear + post front irons. */
function buildLMG() {
  const G = new THREE.Group();
  /* receiver — taller and longer than the rifle's */
  part(G, B(0.128, 0.118, 0.42), GUNMETAL, 0, -0.002, -0.02);
  /* stepped side plates keep the receiver from reading as one skinny cuboid
     head-on while leaving the centre sight channel completely open */
  for (const x of [-0.066, 0.066]) part(G, B(0.018, 0.08, 0.3), STEEL, x, -0.006, -0.035);
  /* Hinged at the rear so the feed cover can actually open during a belt-box
     change instead of rotating as an impossible slab around its centre. */
  const topCover = new THREE.Group();
  topCover.position.set(0, 0.062, 0.15);
  G.add(topCover);
  part(topCover, B(0.136, 0.024, 0.36), GUNMETAL, 0, 0, -0.18);
  /* Fold the carry handle to the left of the 0.115 sight line. Centring it on
     the feed cover put an opaque block directly inside the rear aperture. */
  part(topCover, B(0.03, 0.026, 0.12), POLYMER, -0.042, 0.024, -0.35); // handle base
  part(topCover, B(0.018, 0.02, 0.1), POLYMER, -0.042, 0.046, -0.35); // handle
  /* feed tray + the belt can slung under the left side */
  part(G, B(0.112, 0.034, 0.14), GUNMETAL, -0.012, -0.07, -0.06);
  const mag = new THREE.Group();
  mag.position.set(-0.082, -0.14, -0.05);
  G.add(mag);
  part(mag, B(0.086, 0.148, 0.17), POLYTAN, 0, 0, 0);
  part(mag, B(0.092, 0.016, 0.176), POLYMER, 0, -0.082, 0);
  const lmgMags = makeReloadMagazineSet(mag, G);
  /* belt link strip disappearing into the feed tray */
  part(G, B(0.05, 0.012, 0.06), STEEL, -0.032, -0.058, -0.05);
  /* heat shield with vent slots, barrel, muzzle brake */
  part(G, B(0.112, 0.09, 0.28), GUNMETAL, 0, 0.002, -0.37);
  for (let i = 0; i < 4; i++)
    part(G, B(0.118, 0.016, 0.026), POLYMER, 0, -0.024, -0.47 + i * 0.064);
  part(G, CYLZ(0.019, 0.019, 0.34, 10), STEEL, 0, 0.008, -0.62);
  part(G, CYLZ(0.027, 0.024, 0.07, 10), GUNMETAL, 0, 0.008, -0.79);
  for (let i = 0; i < 3; i++)
    part(G, B(0.056, 0.007, 0.02), GUNMETAL, 0, 0.008, -0.776 + i * 0.022);
  /* folded bipod legs under the barrel */
  part(G, B(0.012, 0.012, 0.16), STEEL, 0.03, -0.05, -0.58);
  part(G, B(0.012, 0.012, 0.16), STEEL, -0.03, -0.05, -0.58);
  /* A bright, open ghost ring and raised front post sit fully above the feed
     cover. RingGeometry gives the aperture visible radial thickness without
     putting an end-cap across the player's sight picture. */
  const rearSight = part(
    G,
    new THREE.RingGeometry(0.019, 0.027, 24),
    STEEL,
    0,
    0.2,
    0.1
  );
  part(G, B(0.012, 0.08, 0.012), GUNMETAL, 0, 0.135, 0.1);
  part(G, B(0.05, 0.025, 0.05), GUNMETAL, 0, 0.09, -0.66);
  for (const x of [-0.025, 0.025]) part(G, B(0.009, 0.1, 0.012), GUNMETAL, x, 0.16, -0.66);
  part(G, B(0.008, 0.075, 0.012), STEEL, 0, 0.1625, -0.66);
  /* charging handle + ejection port */
  const chargeHandle = new THREE.Group();
  chargeHandle.position.set(0.046, 0.02, 0.08);
  G.add(chargeHandle);
  part(chargeHandle, B(0.03, 0.016, 0.05), GUNMETAL, 0, 0, 0);
  part(G, B(0.01, 0.032, 0.08), GUNMETAL, 0.044, 0.01, -0.04);
  /* grip + trigger */
  const grip = new THREE.Group();
  grip.position.set(0, -0.09, 0.06);
  grip.rotation.x = -0.28;
  G.add(grip);
  part(grip, B(0.05, 0.125, 0.064), POLYMER, 0, -0.055, 0);
  part(grip, B(0.052, 0.03, 0.068), GLOVEPAD, 0, -0.108, 0);
  part(G, B(0.014, 0.03, 0.01), STEEL, 0, -0.056, -0.005);
  part(G, B(0.05, 0.01, 0.06), POLYMER, 0, -0.076, -0.01);
  /* skeleton stock + butt pad */
  part(G, B(0.04, 0.05, 0.12), GUNMETAL, 0, 0.01, 0.16);
  part(G, B(0.058, 0.09, 0.15), POLYMER, 0, -0.02, 0.26);
  part(G, B(0.062, 0.106, 0.026), GLOVEPAD, 0, -0.02, 0.34);

  const muzzle = new THREE.Object3D();
  muzzle.position.set(0, 0.008, -0.83);
  G.add(muzzle);
  const eject = new THREE.Object3D();
  eject.position.set(0.055, 0.02, -0.03);
  G.add(eject);

  const hands = new THREE.Group();
  G.add(hands);
  const rh = makeHand(false);
  rh.position.set(0.008, -0.145, 0.085);
  rh.rotation.set(0.3, 0, 0.1);
  hands.add(rh);
  const lh = makeHand(true);
  lh.position.set(-0.01, -0.08, -0.38);
  lh.rotation.set(0.05, 0, -0.18);
  hands.add(lh);

  return {
    group: G,
    muzzle,
    eject,
    mag,
    ...lmgMags,
    topCover,
    chargeHandle,
    aimPoint: rearSight,
    hands,
    leftHand: lh,
    /* carried lower than the rifle — it is a lump of a gun */
    basePos: new THREE.Vector3(0.215, -0.262, -0.96),
    baseRot: new THREE.Vector3(-0.026, 0.082, 0.055),
    /* raised ghost-ring/post line */
    adsPos: new THREE.Vector3(0.0006, -0.2, -0.96),
    adsRot: new THREE.Vector3(0, 0, 0),
    adsRef: 1.08,
  };
}

/* JUG-M134: six barrels around a powered spindle, with a rear motor, carry
   cage, oversized ammunition box and armoured sleeves. The barrel cluster is
   a separate group so the viewmodel animator can give it real spin-up/down. */
function buildJugGatling() {
  const G = new THREE.Group();
  const barrels = new THREE.Group();
  barrels.position.set(0, 0.015, -0.48);
  G.add(barrels);
  for (let i = 0; i < 6; i++) {
    const a = (i * PI) / 3;
    const x = Math.cos(a) * 0.052;
    const y = Math.sin(a) * 0.052;
    part(barrels, CYLZ(0.012, 0.011, 0.72, 8), STEEL, x, y, -0.25);
  }
  part(barrels, CYLZ(0.078, 0.078, 0.045, 16), GUNMETAL, 0, 0, 0.08);
  part(barrels, CYLZ(0.072, 0.072, 0.04, 16), GUNMETAL, 0, 0, -0.55);
  part(barrels, CYLZ(0.028, 0.028, 0.78, 12), GUNMETAL, 0, 0, -0.24);
  /* motor, receiver cage and rear shoulder block */
  part(G, CYLZ(0.13, 0.13, 0.28, 16), GUNMETAL, 0, 0.015, -0.02);
  part(G, B(0.25, 0.2, 0.28), POLYMER, 0, -0.01, 0.17);
  part(G, B(0.29, 0.035, 0.48), GUNMETAL, 0, 0.13, -0.03);
  part(G, B(0.035, 0.22, 0.48), GUNMETAL, -0.13, 0.02, -0.03);
  part(G, B(0.035, 0.22, 0.48), GUNMETAL, 0.13, 0.02, -0.03);
  part(G, B(0.18, 0.13, 0.24), GLOVEPAD, 0, -0.01, 0.39);
  /* feed chute and deep ammunition drum */
  part(G, B(0.12, 0.06, 0.2), STEEL, -0.15, -0.06, 0.06, 0, 0, -0.24);
  part(G, B(0.2, 0.29, 0.28), POLYTAN, -0.19, -0.2, 0.19);
  part(G, B(0.21, 0.025, 0.29), GUNMETAL, -0.19, -0.355, 0.19);
  /* grips and armoured forearms */
  part(G, B(0.045, 0.16, 0.06), POLYMER, 0.105, -0.15, 0.25, -0.3, 0, 0);
  part(G, B(0.045, 0.15, 0.06), POLYMER, -0.105, -0.12, -0.05, -0.18, 0, 0);
  part(G, B(0.17, 0.115, 0.15), POLYMER, 0.2, -0.22, 0.25, 0.06, -0.1, -0.25);
  part(G, B(0.17, 0.115, 0.15), POLYMER, -0.2, -0.18, -0.12, 0.08, 0.12, 0.2);

  const muzzle = new THREE.Object3D();
  muzzle.position.set(0, 0.015, -1.1);
  G.add(muzzle);
  const eject = new THREE.Object3D();
  eject.position.set(-0.14, -0.05, 0.04);
  G.add(eject);
  return {
    group: G,
    muzzle,
    eject,
    barrels,
    barrelSpin: 0,
    hands: new THREE.Group(),
    basePos: new THREE.Vector3(0.25, -0.34, -1.08),
    baseRot: new THREE.Vector3(-0.045, 0.095, 0.075),
    /* Right click braces the weight against the suit: lift the cluster and
       pull the whole weapon closer, without pretending it has iron sights. */
    adsPos: new THREE.Vector3(0.16, -0.235, -0.86),
    adsRot: new THREE.Vector3(-0.025, 0.055, 0.045),
    adsRef: 1.12,
  };
}


/* ==== src/16a-viewmodel-ak.ts ==== */
function buildModernAK() {
  const G = new THREE.Group();
  part(G, B(0.078, 0.096, 0.34), GUNMETAL, 0, 0, -0.02);
  part(G, B(0.072, 0.034, 0.31), POLYMER, 0, 0.061, -0.035);
  part(G, B(0.086, 0.066, 0.1), GUNMETAL, 0, -0.006, -0.205);
  part(G, B(0.01, 0.038, 0.1), STEEL, 0.044, 0.006, 0.05);
  /* Continuous 1913 top rail: receiver and handguard share the same plane. */
  for (let i = 0; i < 15; i++)
    part(G, B(0.058, 0.009, 0.012), POLYMER, 0, 0.083, -0.19 + i * 0.025);
  part(G, B(0.082, 0.084, 0.33), POLYMER, 0, 0, -0.36);
  part(G, B(0.058, 0.014, 0.34), GUNMETAL, 0, 0.056, -0.36);
  for (let i = 0; i < 12; i++)
    part(G, B(0.062, 0.009, 0.012), GUNMETAL, 0, 0.068, -0.51 + i * 0.027);
  for (const x of [-0.043, 0.043])
    for (let i = 0; i < 5; i++)
      part(G, B(0.008, 0.025, 0.034), GLOVEPAD, x, -0.004, -0.48 + i * 0.064);
  part(G, CYLZ(0.018, 0.018, 0.42, 12), STEEL, 0, 0.008, -0.66);
  part(G, CYLZ(0.014, 0.014, 0.32, 10), GUNMETAL, 0, 0.064, -0.54);
  part(G, B(0.05, 0.07, 0.055), GUNMETAL, 0, 0.036, -0.55);

  const compensator = new THREE.Group();
  compensator.position.set(0, 0.008, -0.89);
  G.add(compensator);
  part(compensator, CYLZ(0.026, 0.022, 0.09, 12), GUNMETAL, 0, 0, 0);
  for (let i = 0; i < 3; i++)
    part(compensator, B(0.058, 0.007, 0.018), GUNMETAL, 0, 0.008, -0.026 + i * 0.026);
  const suppressor = new THREE.Group();
  suppressor.position.set(0, 0.008, -0.97);
  suppressor.visible = false;
  G.add(suppressor);
  part(suppressor, CYLZ(0.034, 0.031, 0.25, 16), GUNMETAL, 0, 0, 0);
  for (let i = 0; i < 5; i++)
    part(suppressor, TUBEZ(0.035, 0.008, 16), POLYMER, 0, 0, i * 0.04 - 0.08);

  const makeMag = () => {
    const m = new THREE.Group();
    m.position.set(0, -0.145, -0.055);
    m.rotation.x = 0.23;
    G.add(m);
    part(m, B(0.052, 0.1, 0.09), POLYTAN, 0, 0.005, 0);
    part(m, B(0.054, 0.09, 0.082), POLYTAN, 0, -0.078, 0.018, -0.16, 0, 0);
    for (let i = 0; i < 4; i++)
      part(m, B(0.056, 0.012, 0.01), GLOVEPAD, 0, -0.02 - i * 0.033, 0.025);
    part(m, B(0.058, 0.014, 0.09), POLYMER, 0, -0.13, 0.03);
    return m;
  };
  const mag = makeMag(),
    newMag = makeMag(),
    ejectedMag = makeMag();
  newMag.visible = ejectedMag.visible = false;

  const grip = new THREE.Group();
  grip.position.set(0, -0.09, 0.09);
  grip.rotation.x = -0.3;
  G.add(grip);
  part(grip, B(0.052, 0.13, 0.065), POLYMER, 0, -0.055, 0);
  for (let i = 0; i < 4; i++) part(grip, B(0.054, 0.01, 0.068), GLOVEPAD, 0, -0.035 - i * 0.025, 0);
  part(G, B(0.014, 0.034, 0.01), STEEL, 0, -0.057, 0.005);
  part(G, B(0.052, 0.012, 0.064), POLYMER, 0, -0.075, 0);
  part(G, B(0.026, 0.012, 0.13), STEEL, 0.045, 0.006, 0.03, 0, 0, -0.2);
  const stock = new THREE.Group();
  stock.position.set(0, 0, 0.25);
  G.add(stock);
  part(stock, B(0.055, 0.055, 0.22), POLYMER, 0, 0, 0.08);
  part(stock, B(0.07, 0.12, 0.035), GLOVEPAD, 0, -0.012, 0.2);
  part(stock, B(0.055, 0.032, 0.12), POLYTAN, 0, 0.057, 0.08);

  const optic = buildMicroDot(G, 0.067, -0.07);
  const prism = buildPrismScope(G, 0.132, -0.07);
  const holo = buildHoloSight(G, 0.117, -0.07);
  prism.group.visible = false;
  holo.group.visible = false;
  const verticalGrip = new THREE.Group();
  verticalGrip.position.set(0, -0.075, -0.39);
  verticalGrip.visible = false;
  G.add(verticalGrip);
  part(verticalGrip, B(0.044, 0.14, 0.06), POLYMER, 0, -0.06, 0, -0.12, 0, 0);
  const angledGrip = new THREE.Group();
  angledGrip.position.set(0, -0.07, -0.39);
  G.add(angledGrip);
  part(angledGrip, B(0.052, 0.045, 0.14), POLYMER, 0, -0.018, 0, -0.2, 0, 0);

  const chargeHandle = new THREE.Object3D();
  chargeHandle.position.set(0.052, 0.034, 0.055);
  G.add(chargeHandle);
  part(chargeHandle, CYLZ(0.009, 0.009, 0.055, 8), STEEL, 0.025, 0, 0, 0, PI / 2, 0);
  const muzzle = new THREE.Object3D();
  muzzle.position.set(0, 0.008, -1.02);
  G.add(muzzle);
  const eject = new THREE.Object3D();
  eject.position.set(0.055, 0.025, 0.02);
  G.add(eject);
  const rightGrip = new THREE.Object3D();
  rightGrip.position.set(0.008, -0.145, 0.11);
  G.add(rightGrip);

  const hands = new THREE.Group();
  G.add(hands);
  const rh = makeHand(false),
    lh = makeHand(true);
  rh.position.set(0.008, -0.145, 0.11);
  rh.rotation.set(0.3, 0, 0.1);
  lh.position.set(-0.012, -0.08, -0.39);
  lh.rotation.set(0.05, 0, -0.18);
  hands.add(rh, lh);
  const weaponPivot = new THREE.Group();
  for (const child of [...G.children])
    if (child !== hands && child !== ejectedMag) weaponPivot.add(child);
  G.add(weaponPivot);

  return {
    group: G,
    weaponPivot,
    muzzle,
    eject,
    mag,
    newMag,
    ejectedMag,
    chargeHandle,
    rightGrip,
    hands,
    leftHand: lh,
    rightHand: rh,
    dot: optic.dot,
    dotGlow: optic.dotGlow,
    opticGlass: optic.glass,
    prism,
    holo,
    picatinnyCount: 27,
    attachmentNodes: {
      optic: { micro_dot: optic.group, holo: holo.group, prism_2_5: prism.group },
      muzzle: { compensator, suppressor },
      underbarrel: { angled_grip: angledGrip, vertical_grip: verticalGrip },
    },
    basePos: new THREE.Vector3(0.21, -0.25, -1.0),
    baseRot: new THREE.Vector3(-0.026, 0.085, 0.055),
    adsPos: new THREE.Vector3(0.0006, -0.132, -0.78),
    adsRot: new THREE.Vector3(0, 0, 0),
    adsRef: 0.9,
  };
}


/* ==== src/16b-viewmodels-smg.ts ==== */
/* Compact SMGs are deliberately built as their own silhouettes rather than
   shortened rifle reskins. Both expose detachable magazines, grip anchors and
   real muzzle/ejection transforms to the shared firing/reload animation code. */
function smgHands(G, leftPos, rightPos) {
  const hands = new THREE.Group();
  G.add(hands);
  const rh = makeHand(false);
  rh.position.copy(rightPos);
  rh.rotation.set(0.26, 0.02, 0.1);
  hands.add(rh);
  const lh = makeHand(true);
  lh.position.copy(leftPos);
  lh.rotation.set(0.08, 0.03, -0.18);
  hands.add(lh);
  return { hands, leftHand: lh, rightHand: rh };
}

function smgWeaponPivot(G, hands, looseA, looseB) {
  const pivot = new THREE.Group();
  for (const child of [...G.children])
    if (child !== hands && child !== looseA && child !== looseB) pivot.add(child);
  G.add(pivot);
  return pivot;
}

function buildVector() {
  const G = new THREE.Group();
  /* KRISS-style split receiver: slim upper, deep Super-V lower and the
     characteristic forward magazine well. */
  part(G, B(0.082, 0.072, 0.35), GUNMETAL, 0, 0.035, -0.1);
  part(G, B(0.086, 0.024, 0.37), POLYMER, 0, 0.086, -0.09);
  for (let i = 0; i < 14; i++)
    part(G, B(0.062, 0.01, 0.011), STEEL, 0, 0.103, -0.25 + i * 0.025);
  part(G, B(0.09, 0.185, 0.16), POLYMER, 0, -0.065, -0.12, -0.08, 0, 0);
  part(G, B(0.084, 0.055, 0.16), GUNMETAL, 0, -0.015, -0.245);
  for (let i = 0; i < 4; i++)
    part(G, B(0.092, 0.013, 0.026), GLOVEPAD, 0, -0.055 + i * 0.036, -0.245);
  /* Short barrel, squared shroud and two-port compensator. */
  part(G, B(0.075, 0.068, 0.19), POLYMER, 0, 0.018, -0.36);
  part(G, CYLZ(0.017, 0.017, 0.25, 10), STEEL, 0, 0.02, -0.49);
  part(G, CYLZ(0.025, 0.025, 0.07, 10), GUNMETAL, 0, 0.02, -0.645);
  part(G, B(0.057, 0.012, 0.016), POLYMER, 0, 0.038, -0.636);
  /* Pistol grip behind the magazine well. */
  const grip = new THREE.Group();
  grip.position.set(0, -0.105, 0.01);
  grip.rotation.x = -0.25;
  G.add(grip);
  part(grip, B(0.052, 0.15, 0.068), POLYMER, 0, -0.065, 0);
  for (let i = 0; i < 5; i++)
    part(grip, B(0.055, 0.01, 0.07), GLOVEPAD, 0, -0.02 - i * 0.024, 0);
  const mag = new THREE.Group();
  mag.position.set(0, -0.172, -0.155);
  mag.rotation.x = 0.035;
  G.add(mag);
  part(mag, B(0.044, 0.205, 0.061), GUNMETAL, 0, -0.055, 0);
  part(mag, B(0.05, 0.018, 0.068), POLYMER, 0, -0.164, 0);
  for (let i = 0; i < 5; i++)
    part(mag, B(0.047, 0.008, 0.064), GLOVEPAD, 0, -0.08 - i * 0.028, 0);
  const mags = makeReloadMagazineSet(mag, G);
  /* Skeleton stock and padded shoulder plate. */
  part(G, B(0.07, 0.055, 0.24), POLYMER, 0, 0.025, 0.19);
  part(G, B(0.045, 0.018, 0.27), GUNMETAL, -0.025, 0.035, 0.37, 0.05, 0, 0);
  part(G, B(0.045, 0.018, 0.27), GUNMETAL, 0.025, 0.035, 0.37, -0.05, 0, 0);
  part(G, B(0.075, 0.13, 0.035), GLOVEPAD, 0, 0.005, 0.515);
  /* Hooded iron sights leave an open sight picture. */
  part(G, B(0.012, 0.045, 0.012), STEEL, -0.029, 0.13, 0.025);
  part(G, B(0.012, 0.045, 0.012), STEEL, 0.029, 0.13, 0.025);
  part(G, B(0.008, 0.034, 0.008), ACCENT_R, 0, 0.126, -0.405);
  const chargeHandle = new THREE.Group();
  chargeHandle.position.set(-0.063, 0.05, -0.105);
  G.add(chargeHandle);
  part(chargeHandle, B(0.045, 0.023, 0.04), GUNMETAL, -0.012, 0, 0);
  const muzzle = new THREE.Object3D();
  muzzle.position.set(0, 0.02, -0.685);
  G.add(muzzle);
  const eject = new THREE.Object3D();
  eject.position.set(0.065, 0.055, -0.08);
  G.add(eject);
  const rightGrip = new THREE.Object3D();
  rightGrip.position.set(0.01, -0.17, 0.025);
  G.add(rightGrip);
  const h = smgHands(
    G,
    new THREE.Vector3(-0.012, -0.15, -0.285),
    new THREE.Vector3(0.01, -0.17, 0.025)
  );
  const weaponPivot = smgWeaponPivot(G, h.hands, mags.newMag, mags.ejectedMag);
  return {
    group: G,
    weaponPivot,
    muzzle,
    eject,
    mag,
    ...mags,
    chargeHandle,
    rightGrip,
    ...h,
    basePos: new THREE.Vector3(0.205, -0.25, -0.86),
    baseRot: new THREE.Vector3(-0.025, 0.08, 0.052),
    adsPos: new THREE.Vector3(0.0005, -0.127, -0.82),
    adsRot: new THREE.Vector3(0, 0, 0),
    adsRef: 0.94,
  };
}

function buildP90() {
  const G = new THREE.Group();
  /* The P90 silhouette comes from its broad bullpup shell, thumbhole and
     long translucent horizontal magazine, not from a conventional rifle box. */
  part(G, B(0.145, 0.115, 0.5), POLYMER, 0, -0.008, -0.08);
  part(G, B(0.13, 0.065, 0.24), GLOVEPAD, 0, -0.065, 0.245);
  part(G, B(0.125, 0.035, 0.2), POLYMER, 0, 0.055, 0.255);
  /* Thumbhole is suggested by separated upper/lower stock spars. */
  part(G, B(0.035, 0.17, 0.05), POLYMER, -0.052, -0.12, 0.2, -0.28, 0, 0);
  part(G, B(0.035, 0.17, 0.05), POLYMER, 0.052, -0.12, 0.2, -0.28, 0, 0);
  part(G, B(0.13, 0.065, 0.07), GLOVEPAD, 0, -0.045, 0.405);
  /* Distinctive foregrip arch and forward control pad. */
  part(G, B(0.135, 0.04, 0.16), GUNMETAL, 0, -0.082, -0.28);
  part(G, B(0.04, 0.16, 0.07), POLYMER, -0.048, -0.12, -0.265, -0.2, 0, 0);
  part(G, B(0.04, 0.16, 0.07), POLYMER, 0.048, -0.12, -0.265, -0.2, 0, 0);
  part(G, CYLZ(0.016, 0.016, 0.27, 10), STEEL, 0, 0.004, -0.46);
  part(G, CYLZ(0.024, 0.024, 0.06, 10), GUNMETAL, 0, 0.004, -0.625);
  const mag = new THREE.Group();
  mag.position.set(0, 0.092, -0.04);
  G.add(mag);
  const magMat = new THREE.MeshStandardMaterial({
    color: 0x7a876f,
    roughness: 0.32,
    metalness: 0.08,
    transparent: true,
    opacity: 0.82,
  });
  part(mag, B(0.082, 0.038, 0.47), magMat, 0, 0, 0);
  part(mag, B(0.09, 0.014, 0.475), GUNMETAL, 0, -0.024, 0);
  part(mag, CYLZ(0.026, 0.026, 0.018, 12), STEEL, 0, 0.012, 0.188);
  for (let i = 0; i < 10; i++)
    part(mag, B(0.071, 0.006, 0.012), GLOVEPAD, 0, 0.021, -0.19 + i * 0.041);
  const mags = makeReloadMagazineSet(mag, G);
  /* Open integrated sight bridge. The centre is real empty space. */
  part(G, B(0.018, 0.065, 0.19), GUNMETAL, -0.055, 0.09, -0.15);
  part(G, B(0.018, 0.065, 0.19), GUNMETAL, 0.055, 0.09, -0.15);
  part(G, B(0.12, 0.018, 0.07), GUNMETAL, 0, 0.128, -0.08);
  part(G, B(0.01, 0.034, 0.01), ACCENT_R, 0, 0.13, -0.39);
  const chargeHandle = new THREE.Group();
  chargeHandle.position.set(-0.085, 0.02, -0.24);
  G.add(chargeHandle);
  part(chargeHandle, B(0.04, 0.022, 0.045), GUNMETAL, -0.012, 0, 0);
  const muzzle = new THREE.Object3D();
  muzzle.position.set(0, 0.004, -0.665);
  G.add(muzzle);
  const eject = new THREE.Object3D();
  eject.position.set(0.018, -0.095, -0.04);
  G.add(eject);
  const rightGrip = new THREE.Object3D();
  rightGrip.position.set(0.02, -0.13, 0.18);
  G.add(rightGrip);
  const h = smgHands(
    G,
    new THREE.Vector3(-0.025, -0.14, -0.29),
    new THREE.Vector3(0.02, -0.13, 0.18)
  );
  const weaponPivot = smgWeaponPivot(G, h.hands, mags.newMag, mags.ejectedMag);
  return {
    group: G,
    weaponPivot,
    muzzle,
    eject,
    mag,
    ...mags,
    chargeHandle,
    rightGrip,
    ...h,
    basePos: new THREE.Vector3(0.2, -0.25, -0.86),
    baseRot: new THREE.Vector3(-0.024, 0.08, 0.052),
    adsPos: new THREE.Vector3(0.0005, -0.128, -0.83),
    adsRot: new THREE.Vector3(0, 0, 0),
    adsRef: 0.95,
  };
}


export {
  buildRifle,
  buildShotgun,
  buildPistol,
  buildSniper,
  buildLMG,
  buildModernAK,
  buildVector,
  buildP90,
  buildJugGatling,
};
