/* Auto-generated by tools/train-ground-model.py — do not edit by hand. */
export const GROUND_MODEL = {
  featureNames: ["isRock", "isLog", "size", "halfW", "halfD", "height", "bottomOffset", "ground", "rayBias", "slope", "curv", "ringMean", "ringMin", "ringMax"],
  means: [0.92857143, 0.07142857, 4.04283675, 1.05447064, 1.16871895, 2.46106855, -1.23053427, 0.09098305, 0.01762943, 0.20566606, 0.0025199, 0.08846314, -0.01048065, 0.19518541],
  scales: [0.25753938, 0.25753938, 0.83749935, 0.26394195, 0.36260524, 0.52271864, 0.26135932, 0.16710463, 0.21462127, 0.09273367, 0.01283823, 0.1650641, 0.17184016, 0.16629231],
  coef: [-0.01399273, 0.01399273, -0.01409229, -0.00642518, -0.01348519, -0.02006327, 0.02006327, 0.0088016, 0.00535737, -0.0078261, 0.01341643, 0.00786691, 0.00731287, 0.00319258],
  intercept: -0.23928571,
  alpha: 8.0,
  trainMAE: 0.0747,
  testMAE: 0.1532,
};

export function predictGroundDelta(features: Record<string, number>) {
  const m = GROUND_MODEL;
  let z = 0;
  for (let i = 0; i < m.featureNames.length; i++) {
    const raw = features[m.featureNames[i]] ?? 0;
    const s = m.scales[i] || 1;
    z += ((raw - m.means[i]) / s) * m.coef[i];
  }
  return z + m.intercept;
}
