import { execFileSync } from 'node:child_process';
import { cp, mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';

const output = new URL('../dist/', import.meta.url);
const root = new URL('../', import.meta.url);
const compiler = fileURLToPath(new URL('../node_modules/typescript/bin/tsc', import.meta.url));

/* Shared weapon data is the single source. Legacy's single-file build receives
   a generated declaration so it cannot drift from the campaign values. */
const weapons = JSON.parse(await readFile(new URL('../shared/weapons.json', import.meta.url), 'utf-8'));
const generated = ['// GENERATED by scripts/build.mjs from shared/weapons.json — do not edit.', 'const SHARED_WEAPON_BASE = {'];
for (const w of Object.values(weapons.weapons)) {
  generated.push(
    `  ${JSON.stringify(w.legacyId)}: { id: ${JSON.stringify(w.legacyId)}, name: ${JSON.stringify(w.name)}, magSize: ${w.magSize}, reserve: ${w.reserve}, maxReserve: ${w.maxReserve}, damage: ${w.damage}, pellets: ${w.pellets}, rpm: ${w.rpm}, auto: ${w.auto} },`
  );
}
generated.push('};');
await writeFile(new URL('../src/generated-weapons.ts', import.meta.url), generated.join('\n') + '\n');

/* Shared movement data is the same deal: legacy constants are generated from
   the JSON the campaign imports directly. */
const movement = JSON.parse(await readFile(new URL('../shared/movement.json', import.meta.url), 'utf-8'));
const movementText = [
  '// GENERATED by scripts/build.mjs from shared/movement.json — do not edit.',
  'const SHARED_MOVEMENT = ' + JSON.stringify(movement, null, 2) + ';',
  '',
].join('\n');
await writeFile(new URL('../src/generated-movement.ts', import.meta.url), movementText);

await rm(output, { recursive: true, force: true });
await mkdir(new URL('js/', output), { recursive: true });

execFileSync(process.execPath, [compiler, '--project', 'tsconfig.json'], {
  cwd: fileURLToPath(root),
  stdio: 'inherit',
});

for (const file of ['index.html', 'cover-total-frontline.png']) {
  await cp(new URL(`../${file}`, import.meta.url), new URL(file, output));
}

for (const directory of ['screenshots', 'assets', 'shared']) {
  await cp(new URL(`../${directory}/`, import.meta.url), new URL(`${directory}/`, output), {
    recursive: true,
  });
}

console.log('Built static game into dist/');
