import hashlib
import json
import math
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "data" / "ground-dataset.json"
OUT_TS = ROOT / "src" / "ground-model.ts"

FEATURES = [
    "isRock",
    "isLog",
    "size",
    "halfW",
    "halfD",
    "height",
    "bottomOffset",
    "ground",
    "rayBias",
    "slope",
    "curv",
    "ringMean",
    "ringMin",
    "ringMax",
]

raw = json.loads(DATA.read_text(encoding="utf-8"))
rows = raw["rows"]
X = np.array([[r["features"][f] for f in FEATURES] for r in rows], dtype=np.float64)
y = np.array([r["targetDelta"] for r in rows], dtype=np.float64)
keys = [r["key"] for r in rows]
kinds = [r["kind"] for r in rows]

# deterministic 80/20 split, balanced enough for 18 samples
idx = list(range(len(rows)))
idx.sort(key=lambda i: hashlib.sha256(keys[i].encode()).hexdigest())
test_n = max(1, round(len(idx) * 0.2))
test_idx = idx[:test_n]
train_idx = idx[test_n:]
print(f"train={len(train_idx)} test={len(test_idx)}")

X_train, y_train = X[train_idx], y[train_idx]
X_test, y_test = X[test_idx], y[test_idx]

mu = X_train.mean(axis=0)
sd = X_train.std(axis=0)
sd[sd < 1e-9] = 1.0


def standardize(a):
    return (a - mu) / sd


Z_train = standardize(X_train)
Z_test = standardize(X_test)


def ridge_fit_predict(Z, y, alpha):
    n, d = Z.shape
    A = Z.T @ Z + alpha * np.eye(d)
    b = Z.T @ y
    w = np.linalg.solve(A, b)
    b0 = y.mean() - Z.mean(axis=0) @ w
    return w, b0


def ridge_loocv(Z, y, alpha):
    n = len(y)
    pred = np.zeros(n)
    for i in range(n):
        m = np.ones(n, dtype=bool)
        m[i] = False
        w, b0 = ridge_fit_predict(Z[m], y[m], alpha)
        pred[i] = Z[i] @ w + b0
    return np.mean(np.abs(pred - y))


# choose alpha on the train set only via leave-one-out
alphas = [0.05, 0.1, 0.25, 0.5, 1.0, 2.0, 4.0, 8.0]
loocv = {a: ridge_loocv(Z_train, y_train, a) for a in alphas}
alpha = min(loocv, key=loocv.get)
print("alpha search:", {a: round(v, 3) for a, v in loocv.items()}, "chosen", alpha)

coef, intercept = ridge_fit_predict(Z_train, y_train, alpha)
train_pred = Z_train @ coef + intercept
test_pred = Z_test @ coef + intercept


def metrics(y_true, y_pred):
    e = y_true - y_pred
    return {
        "mae": float(np.mean(np.abs(e))),
        "rmse": float(np.sqrt(np.mean(e**2))),
        "max": float(np.max(np.abs(e))),
    }


train_m = metrics(y_train, train_pred)
test_m = metrics(y_test, test_pred)

# baselines for comparison
rock_mean = y_train[np.array(kinds)[train_idx] == "rock"].mean()
log_mean = y_train[np.array(kinds)[train_idx] == "log"].mean()
base_pred = np.where(np.array(kinds)[train_idx] == "rock", rock_mean, log_mean)
train_base = metrics(y_train, base_pred)
print("train metrics:", {k: round(v, 3) for k, v in train_m.items()})
print("test metrics:", {k: round(v, 3) for k, v in test_m.items()})
print("train kind-mean baseline:", {k: round(v, 3) for k, v in train_base.items()})

# export deterministic TS model
lines = [
    "/* Auto-generated by tools/train-ground-model.py — do not edit by hand. */",
    f"export const GROUND_MODEL = {{",
    f"  featureNames: {json.dumps(FEATURES)},",
    f"  means: {json.dumps([round(float(x), 8) for x in mu])},",
    f"  scales: {json.dumps([round(float(x), 8) for x in sd])},",
    f"  coef: {json.dumps([round(float(x), 8) for x in coef])},",
    f"  intercept: {round(float(intercept), 8)},",
    f"  alpha: {alpha},",
    f"  trainMAE: {round(train_m['mae'], 4)},",
    f"  testMAE: {round(test_m['mae'], 4)},",
    "};",
    "",
    "export function predictGroundDelta(features: Record<string, number>) {",    "  const m = GROUND_MODEL;",
    "  let z = 0;",
    "  for (let i = 0; i < m.featureNames.length; i++) {",
    "    const raw = features[m.featureNames[i]] ?? 0;",
    "    const s = m.scales[i] || 1;",
    "    z += ((raw - m.means[i]) / s) * m.coef[i];",
    "  }",
    "  return z + m.intercept;",
    "}",
    "",
]
OUT_TS.write_text("\n".join(lines), encoding="utf-8")
print(f"wrote {OUT_TS}")
