// GENERATED by scripts/generate-gameplay.mjs from shared/gameplay — do not edit.
'use strict';
const Gameplay = (() => {

/* ==== shared/gameplay/math.ts ==== */
const PI = Math.PI;

function clamp(v: number, lo: number, hi: number) {
  return v < lo ? lo : v > hi ? hi : v;
}

function lerp(a: number, b: number, t: number) {
  return a + (b - a) * t;
}

function damp(cur: number, tgt: number, lambda: number, dt: number) {
  return lerp(cur, tgt, 1 - Math.exp(-lambda * dt));
}

function easeOutCubic(t: number) {
  return 1 - (1 - t) ** 3;
}

function easeInOutCubic(t: number) {
  return t < 0.5 ? 4 * t * t * t : 1 - (-2 * t + 2) ** 3 / 2;
}

function rand(a: number, b: number) {
  return a + Math.random() * (b - a);
}

function randI(a: number, b: number) {
  return Math.floor(rand(a, b + 1));
}


/* ==== shared/gameplay/types.ts ==== */
interface Vec3 {
  x: number;
  y: number;
  z: number;
}

/** Height-aware world queries. Yard AABB and the valley heightfield both adapt this. */
interface WorldQuery {
  groundY(x: number, z: number, probeY?: number): number | null;
  ceilingY(x: number, z: number, fromY: number): number;
  blocked(x: number, z: number, y0: number, y1: number, radius: number): boolean;
  depenetrate(pos: Vec3, radius: number, y0: number, y1: number): void;
  clampHorizontal(pos: Vec3, padding: number): void;
}

interface MovementTuning {
  speeds: { walk: number; sprint: number; crouch: number; prone: number };
  physics: {
    acceleration: number;
    airAcceleration: number;
    friction: number;
    gravity: number;
    jumpVelocity: number;
    doubleJumpVelocity: number;
  };
  stance: {
    standHeight: number;
    crouchHeight: number;
    proneHeight: number;
    radius: number;
    baseFov: number;
  };
}

interface LocoInput {
  forward: boolean;
  back: boolean;
  left: boolean;
  right: boolean;
  sprint: boolean;
  jumpHeld: boolean;
  jumpPressed: boolean;
  crouch: boolean;
  pronePressed: boolean;
}

interface LocoState {
  pos: Vec3;
  vel: Vec3;
  yaw: number;
  crouch: boolean;
  prone: boolean;
  sprint: boolean;
  height: number;
  onGround: boolean;
  jumpsLeft: number;
  mantleT: number;
  mantleDur: number;
  mantleFrom: Vec3;
  mantleTo: Vec3;
  mantleTilt: number;
  ads: boolean;
  adsEase: number;
  reloading: boolean;
  sprintFireRaise: number;
  canSprint: boolean;
  canProne: boolean;
  canMantle: boolean;
  canDoubleJump: boolean;
  jumpScale: number;
  speedScale: number;
}

interface LocoEvents {
  onJump?: () => void;
  onLand?: (force: number) => void;
  onMantleStart?: () => void;
  onMantleEnd?: () => void;
}

interface SpreadWeapon {
  spreadBase: number;
  moveSpread: number;
  airSpread: number;
  crouchMult: number;
  adsSpread: number;
}

interface RecoilImpulse {
  velP: number;
  velY: number;
  fovKick: number;
  shake: number;
}


/* ==== shared/gameplay/ids.ts ==== */
/** Campaign ids → single-player family ids used by reload stages and fire rules. */
const FAMILY: Record<string, string> = {
  m4: 'rifle',
  ks12: 'shotgun',
  p9: 'pistol',
  sr7: 'sniper',
  ak12: 'ak',
  p90: 'p90',
  rifle: 'rifle',
  shotgun: 'shotgun',
  pistol: 'pistol',
  sniper: 'sniper',
  ak: 'ak',
  lmg: 'lmg',
  vector: 'vector',
  jug_gatling: 'jug_gatling',
};

function weaponFamily(id: string) {
  return FAMILY[id] || id;
}

function isShotgun(id: string) {
  return weaponFamily(id) === 'shotgun';
}


/* ==== shared/gameplay/ballistics.ts ==== */

const LEG_MULTIPLIER = 0.78;

type SurfaceKind = 'glass' | 'wood' | 'panel' | 'metal' | 'soft' | 'structure';

interface SurfaceSpec {
  kind: SurfaceKind;
  resistance: number;
}

interface PenetrationHit {
  id: string;
  liveEnemy: boolean;
  key?: string;
  transparent?: boolean;
  opacity?: number;
}

interface PenetrationSurface {
  index: number;
  kind: SurfaceKind;
  penetrated: boolean;
}

interface PenetrationResult {
  terminalIndex: number | null;
  enemy: boolean;
  surfaces: PenetrationSurface[];
  damageScale: number;
  energy: number;
}

const WOOD = new Set(['wood', 'woodDk', 'crate', 'card', 'bark']);
const PANEL = new Set(['sidY', 'sidB', 'trim', 'ceil', 'roof']);
const METAL = new Set([
  'container',
  'barrel',
  'metal',
  'darkMetal',
  'rust',
  'steel',
  'dark',
  'yellow',
  'green',
  'busGrn',
  'truckWh',
  'truckTl',
  'carPink',
  'carTeal',
  'red',
]);
const SOFT = new Set(['rubber', 'sack', 'plastic']);

function ballisticSurfaceFromKey(
  key: string,
  transparent = false,
  opacity = 1
): SurfaceSpec {
  if (key.includes('glass') || key === 'fence' || key === 'leaf' || key === 'leaf2')
    return { kind: 'glass', resistance: 0.07 };
  if (WOOD.has(key)) return { kind: 'wood', resistance: 0.34 };
  if (PANEL.has(key)) return { kind: 'panel', resistance: 0.48 };
  if (METAL.has(key)) return { kind: 'metal', resistance: 0.58 };
  if (SOFT.has(key)) return { kind: 'soft', resistance: 0.22 };
  if (transparent && opacity < 0.65) return { kind: 'glass', resistance: 0.07 };
  return { kind: 'structure', resistance: Number.POSITIVE_INFINITY };
}

function weaponPenetrationFor(id: string) {
  const family = weaponFamily(id);
  if (family === 'sniper') return 1.85;
  if (family === 'jug_gatling') return 1.45;
  if (family === 'ak' || family === 'lmg') return 1.16;
  if (family === 'rifle') return 1.02;
  if (family === 'p90') return 0.72;
  if (family === 'vector') return 0.66;
  if (family === 'pistol') return 0.54;
  return 0.28;
}

function damageFalloff(dist: number, start: number, range: number, min: number) {
  return clamp(1 - Math.max(0, dist - start) / Math.max(1, range), min, 1);
}

function partMultiplier(head: boolean, legs: boolean, headMult: number) {
  if (head) return headMult;
  if (legs) return LEG_MULTIPLIER;
  return 1;
}

function tracePenetrations(hits: PenetrationHit[], weaponId: string): PenetrationResult {
  let energy = weaponPenetrationFor(weaponId);
  let damageScale = 1;
  const surfaces: PenetrationSurface[] = [];
  const visited = new Set<string>();
  for (let i = 0; i < hits.length; i++) {
    const hit = hits[i];
    if (hit.liveEnemy) return { terminalIndex: i, enemy: true, surfaces, damageScale, energy };
    if (visited.has(hit.id)) continue;
    visited.add(hit.id);
    const surface = ballisticSurfaceFromKey(hit.key || '', !!hit.transparent, hit.opacity ?? 1);
    const penetrated = Number.isFinite(surface.resistance) && energy > surface.resistance;
    surfaces.push({ index: i, kind: surface.kind, penetrated });
    if (!penetrated) return { terminalIndex: i, enemy: false, surfaces, damageScale, energy: 0 };
    damageScale *= clamp(1 - (surface.resistance / energy) * 0.48, 0.28, 0.9);
    energy -= surface.resistance;
  }
  return { terminalIndex: null, enemy: false, surfaces, damageScale, energy };
}


/* ==== shared/gameplay/stance.ts ==== */
/** Single-player stance multipliers from src/19b-stance.ts. */

function stanceSpreadMultiplier(prone: boolean, crouch: boolean, crouchMult: number) {
  if (prone) return Math.max(0.28, (crouchMult || 0.7) * 0.55);
  if (crouch) return crouchMult || 0.7;
  return 1;
}

function stanceRecoilMultiplier(prone: boolean, crouch: boolean) {
  return prone ? 0.56 : crouch ? 0.8 : 1;
}

function stanceRecoveryMultiplier(prone: boolean, crouch: boolean) {
  return prone ? 1.65 : crouch ? 1.28 : 1;
}


/* ==== shared/gameplay/spread.ts ==== */

/** Hip-fire cone used by both shooters: heat + move + air + stance + ADS. */
function currentSpread(
  heat: number,
  weapon: SpreadWeapon,
  speed: number,
  grounded: boolean,
  prone: boolean,
  crouch: boolean,
  adsEase: number
) {
  let spread = heat + (speed / 7) * weapon.moveSpread;
  if (!grounded) spread += weapon.airSpread;
  spread *= stanceSpreadMultiplier(prone, crouch, weapon.crouchMult);
  spread *= 1 + (weapon.adsSpread - 1) * adsEase;
  return spread;
}


/* ==== shared/gameplay/recoil.ts ==== */

function currentRecoilScale(
  adsRecoil: number,
  adsEase: number,
  stanceMult: number,
  magnified = false
) {
  const adsStability = lerp(1, adsRecoil ?? 0.62, adsEase);
  const magnifiedComp = magnified ? lerp(1, 0.86, adsEase) : 1;
  return adsStability * magnifiedComp * stanceMult;
}

/** Same burst-shaped camera kick as src/23-player-update + fireWeapon. */
function recoilImpulse(
  camPitch: number,
  camYaw: number,
  fovKick: number,
  scale: number,
  burst: number,
  shakeAmt: number,
  adsEase: number
): RecoilImpulse {
  const vert = burst === 0 ? 1.55 : burst < 4 ? 1.12 : 0.82 + Math.sin(burst * 0.9) * 0.1;
  const drift = Math.sin(burst * 0.62) * 0.85 + Math.sin(burst * 0.23 + 1.1) * 0.45;
  return {
    velP: camPitch * 38 * vert * scale,
    velY: (drift + (Math.random() - 0.5) * 0.55) * camYaw * 38 * scale,
    fovKick: fovKick * scale,
    shake: shakeAmt * 0.5 * lerp(1, 0.68, adsEase),
  };
}


/* ==== shared/gameplay/collide.ts ==== */

/** Axis-separated slide from src/13-map-apply.ts. Depenetration stays in the adapter. */
function moveSlide(
  world: WorldQuery,
  pos: Vec3,
  dx: number,
  dz: number,
  radius: number,
  height: number
) {
  const y0 = pos.y + 0.3;
  const y1 = pos.y + height - 0.05;
  if (world.blocked(pos.x, pos.z, y0, y1, radius)) {
    pos.x += dx;
    pos.z += dz;
    world.depenetrate(pos, radius, y0, y1);
    return;
  }
  if (dx !== 0 && !world.blocked(pos.x + dx, pos.z, y0, y1, radius)) pos.x += dx;
  if (dz !== 0 && !world.blocked(pos.x, pos.z + dz, y0, y1, radius)) pos.z += dz;
}


/* ==== shared/gameplay/movement.ts ==== */

const MANTLE_RISE = 1.95;
const MANTLE_MIN = 0.45;
const STEP_HEIGHT = 0.62;
const RELOAD_MOVE_SCALE = 0.86;
const ADS_MOVE_PENALTY = 0.4;

function findMantle(
  state: LocoState,
  world: WorldQuery,
  standHeight: number,
  radius: number
): Vec3 | null {
  const fx = -Math.sin(state.yaw);
  const fz = -Math.cos(state.yaw);
  const feet = state.pos.y;
  for (let i = 0; i < 3; i++) {
    const reach = 0.55 + i * 0.25;
    const px = state.pos.x + fx * reach;
    const pz = state.pos.z + fz * reach;
    const top = world.groundY(px, pz, feet + MANTLE_RISE);
    if (top === null) continue;
    const rise = top - feet;
    if (rise < MANTLE_MIN || rise > MANTLE_RISE) continue;
    if (world.blocked(px, pz, top + 0.1, top + standHeight - 0.06, radius * 0.92)) continue;
    const ahead = world.groundY(px + fx * 0.35, pz + fz * 0.35, top + 0.35);
    if (ahead === null || ahead < top - 0.45) continue;
    return { x: px + fx * 0.28, y: top + 0.02, z: pz + fz * 0.28 };
  }
  return null;
}

function beginMantle(state: LocoState, target: Vec3, events: LocoEvents) {
  state.mantleFrom = { x: state.pos.x, y: state.pos.y, z: state.pos.z };
  state.mantleTo = { x: target.x, y: target.y, z: target.z };
  const rise = Math.max(0.2, target.y - state.pos.y);
  state.mantleDur = clamp(0.26 + rise * 0.13, 0.28, 0.55);
  state.mantleT = 1e-4;
  state.vel.x = state.vel.y = state.vel.z = 0;
  state.onGround = false;
  state.jumpsLeft = 0;
  events.onMantleStart?.();
}

function createLocoState(x: number, y: number, z: number, standHeight: number): LocoState {
  return {
    pos: { x, y, z },
    vel: { x: 0, y: 0, z: 0 },
    yaw: 0,
    crouch: false,
    prone: false,
    sprint: false,
    height: standHeight,
    onGround: true,
    jumpsLeft: 1,
    mantleT: 0,
    mantleDur: 0.4,
    mantleFrom: { x, y, z },
    mantleTo: { x, y, z },
    mantleTilt: 0,
    ads: false,
    adsEase: 0,
    reloading: false,
    sprintFireRaise: 0,
    canSprint: true,
    canProne: true,
    canMantle: true,
    canDoubleJump: true,
    jumpScale: 1,
    speedScale: 1,
  };
}

function stepLocomotion(
  dt: number,
  state: LocoState,
  input: LocoInput,
  world: WorldQuery,
  tuning: MovementTuning,
  events: LocoEvents = {}
) {
  const SPEED = tuning.speeds;
  const PHYS = tuning.physics;
  const STANCE = tuning.stance;

  if (state.sprintFireRaise > 0) state.sprintFireRaise = Math.max(0, state.sprintFireRaise - dt);

  if (input.pronePressed) {
    if (state.prone) {
      const ceil = world.ceilingY(state.pos.x, state.pos.z, state.pos.y + STANCE.proneHeight);
      if (ceil - state.pos.y > STANCE.crouchHeight + 0.1) {
        state.prone = false;
        state.crouch = true;
      }
    } else if (state.canProne && state.onGround && state.mantleT <= 0) {
      state.prone = true;
      state.crouch = false;
      state.sprint = false;
    }
  }
  if (!state.canProne) state.prone = false;
  if (input.crouch && state.prone) {
    const ceil = world.ceilingY(state.pos.x, state.pos.z, state.pos.y + STANCE.proneHeight);
    if (ceil - state.pos.y > STANCE.crouchHeight + 0.1) state.prone = false;
  }

  const wantSprint =
    state.canSprint &&
    input.sprint &&
    !input.crouch &&
    !state.prone &&
    !state.ads &&
    input.forward &&
    state.sprintFireRaise <= 0;

  if (!state.prone && !input.crouch && state.crouch) {
    const ceil = world.ceilingY(state.pos.x, state.pos.z, state.pos.y + STANCE.crouchHeight);
    if (ceil - state.pos.y > STANCE.standHeight + 0.1) state.crouch = false;
  } else if (!state.prone) state.crouch = input.crouch;
  state.sprint = wantSprint && !state.crouch && !state.prone;

  const stanceHeight = state.prone
    ? STANCE.proneHeight
    : state.crouch
      ? STANCE.crouchHeight
      : STANCE.standHeight;
  state.height = damp(state.height, stanceHeight, 13, dt);

  const forward = (input.forward ? 1 : 0) - (input.back ? 1 : 0);
  const strafe = (input.right ? 1 : 0) - (input.left ? 1 : 0);
  let wx = -Math.sin(state.yaw) * forward + Math.cos(state.yaw) * strafe;
  let wz = -Math.cos(state.yaw) * forward - Math.sin(state.yaw) * strafe;
  const wl = Math.hypot(wx, wz);
  if (wl > 0) {
    wx /= wl;
    wz /= wl;
  }

  let maxSpeed = state.prone
    ? SPEED.prone
    : state.crouch
      ? SPEED.crouch
      : state.sprint
        ? SPEED.sprint
        : SPEED.walk;
  if (state.reloading) maxSpeed *= RELOAD_MOVE_SCALE;
  maxSpeed *= 1 - ADS_MOVE_PENALTY * state.adsEase;
  maxSpeed *= state.speedScale;

  const accel = state.onGround ? PHYS.acceleration : PHYS.airAcceleration;
  if (wl > 0) {
    state.vel.x += wx * accel * dt;
    state.vel.z += wz * accel * dt;
  }
  if (state.onGround) {
    const sp = Math.hypot(state.vel.x, state.vel.z);
    if (sp > 0) {
      const drop = sp * PHYS.friction * dt * (wl > 0 ? 0.55 : 1);
      const k = Math.max(0, sp - drop) / sp;
      state.vel.x *= k;
      state.vel.z *= k;
    }
  }
  {
    const sp = Math.hypot(state.vel.x, state.vel.z);
    if (sp > maxSpeed) {
      const k = maxSpeed / sp;
      state.vel.x *= k;
      state.vel.z *= k;
    }
  }

  if (state.onGround) state.jumpsLeft = 1;
  let jumpedNow = false;
  if (input.jumpHeld && state.onGround && !state.crouch && !state.prone) {
    state.vel.y = PHYS.jumpVelocity * state.jumpScale;
    state.onGround = false;
    state.jumpsLeft = 1;
    jumpedNow = true;
    events.onJump?.();
  }
  if (!state.prone && !jumpedNow && !state.onGround && state.mantleT <= 0) {
    if (state.canMantle && input.jumpHeld && state.vel.y < 2.6) {
      const led = findMantle(state, world, STANCE.standHeight, STANCE.radius);
      if (led) beginMantle(state, led, events);
    }
    if (state.canDoubleJump && state.mantleT <= 0 && input.jumpPressed && state.jumpsLeft > 0) {
      state.jumpsLeft--;
      state.vel.y = PHYS.doubleJumpVelocity;
      events.onJump?.();
    }
  }

  state.vel.y += PHYS.gravity * dt;
  if (state.vel.y < -46) state.vel.y = -46;

  if (state.mantleT > 0) {
    state.mantleT += dt;
    const k = clamp(state.mantleT / state.mantleDur, 0, 1);
    const ku = easeOutCubic(clamp(k * 1.42, 0, 1));
    const kf = easeInOutCubic(clamp((k - 0.3) / 0.7, 0, 1));
    state.pos.y = lerp(state.mantleFrom.y, state.mantleTo.y, ku);
    state.pos.x = lerp(state.mantleFrom.x, state.mantleTo.x, kf);
    state.pos.z = lerp(state.mantleFrom.z, state.mantleTo.z, kf);
    state.vel.x = state.vel.y = state.vel.z = 0;
    state.mantleTilt = Math.sin(k * PI) * 0.085;
    if (k >= 1) {
      state.mantleT = 0;
      state.mantleTilt = 0;
      state.onGround = true;
      state.jumpsLeft = 1;
      events.onMantleEnd?.();
    } else state.onGround = false;
  } else {
    moveSlide(world, state.pos, state.vel.x * dt, state.vel.z * dt, STANCE.radius, state.height);
    world.clampHorizontal(state.pos, STANCE.radius + 0.44);

    const prevVy = state.vel.y;
    const prevY = state.pos.y;
    state.pos.y += state.vel.y * dt;
    if (state.vel.y > 0) {
      const ceil = world.ceilingY(state.pos.x, state.pos.z, state.pos.y + state.height);
      if (state.pos.y + state.height > ceil) {
        state.pos.y = ceil - state.height - 0.01;
        state.vel.y = 0;
      }
    }
    const step = state.onGround && state.vel.y <= 0 ? STEP_HEIGHT : 0;
    const gy = world.groundY(state.pos.x, state.pos.z, Math.max(prevY, state.pos.y) + step);
    const floorY = gy === null ? 0 : gy;
    if (state.pos.y <= floorY + 0.02) {
      if (!state.onGround && prevVy < -3) events.onLand?.(clamp(-prevVy / 16, 0, 1));
      state.pos.y = floorY;
      state.vel.y = 0;
      state.onGround = true;
    } else {
      state.onGround = false;
    }
  }

  {
    const y0 = state.pos.y + 0.3;
    const y1 = state.pos.y + state.height - 0.05;
    if (world.blocked(state.pos.x, state.pos.z, y0, y1, STANCE.radius))
      world.depenetrate(state.pos, STANCE.radius, y0, y1);
  }
}


/* ==== shared/gameplay/controller.ts ==== */
/* Extracted from the verified single-player update in src/23-player-update.ts.
   Campaign and legacy both call these functions; hosts only supply world/input. */

const LOOK_SENS = 0.0022;
const BREATH_TIME = 3;

interface ViewWeapon {
  adsTime: number;
  adsFov: number;
  scope?: boolean;
  bracedAim?: boolean;
}

interface ViewState {
  yaw: number;
  pitch: number;
  recoilPitch: number;
  recoilYaw: number;
  recoilVelP: number;
  recoilVelY: number;
  fovKick: number;
  shake: number;
  landShake: number;
  shakeSeed: number;
  ads: boolean;
  adsK: number;
  adsEase: number;
  scoped: boolean;
  breath: number;
  breathHeld: boolean;
  breathLock: boolean;
  swayT: number;
  swayAmp: number;
  scopeSwayX: number;
  scopeSwayY: number;
  bobAmp: number;
  stepPhase: number;
  eye: number;
  hipFov: number;
  fov: number;
  sensScale: number;
  mouseDX: number;
  mouseDY: number;
}

interface ViewPose {
  x: number;
  y: number;
  z: number;
  pitch: number;
  yaw: number;
  roll: number;
  fov: number;
  footstep: { vol: number; pan: number } | null;
}

function createViewState(baseFov: number, standHeight: number): ViewState {
  return {
    yaw: 0,
    pitch: -0.06,
    recoilPitch: 0,
    recoilYaw: 0,
    recoilVelP: 0,
    recoilVelY: 0,
    fovKick: 0,
    shake: 0,
    landShake: 0,
    shakeSeed: Math.random() * 100,
    ads: false,
    adsK: 0,
    adsEase: 0,
    scoped: false,
    breath: 0,
    breathHeld: false,
    breathLock: false,
    swayT: 0,
    swayAmp: 1,
    scopeSwayX: 0,
    scopeSwayY: 0,
    bobAmp: 0,
    stepPhase: 0,
    eye: standHeight * 0.92,
    hipFov: baseFov,
    fov: baseFov,
    sensScale: 1,
    mouseDX: 0,
    mouseDY: 0,
  };
}

function accumulateLook(view: ViewState, dx: number, dy: number) {
  view.mouseDX = clamp(view.mouseDX + clamp(dx || 0, -90, 90), -180, 180);
  view.mouseDY = clamp(view.mouseDY + clamp(dy || 0, -90, 90), -180, 180);
}

/** Single-player look / ADS / breath. Mouse is applied once per frame. */
function stepLook(
  dt: number,
  view: ViewState,
  weapon: ViewWeapon,
  opts: { shiftDown: boolean; reloading: boolean; switching: boolean; dead?: boolean },
  mouseSens: number,
  baseFov: number
) {
  view.yaw -= view.mouseDX * LOOK_SENS * mouseSens * view.sensScale;
  view.pitch -= view.mouseDY * LOOK_SENS * mouseSens * view.sensScale;
  view.pitch = clamp(view.pitch, -PI / 2 + 0.02, PI / 2 - 0.02);
  view.mouseDX = 0;
  view.mouseDY = 0;

  view.recoilVelP = damp(view.recoilVelP, 0, 16, dt);
  view.recoilVelY = damp(view.recoilVelY, 0, 16, dt);
  view.recoilPitch += view.recoilVelP * dt;
  view.recoilYaw += view.recoilVelY * dt;
  view.recoilPitch = damp(view.recoilPitch, 0, 6.5, dt);
  view.recoilYaw = damp(view.recoilYaw, 0, 6.5, dt);

  if (view.ads && (opts.reloading || opts.dead)) view.ads = false;
  const adsWant = view.ads && !opts.switching;
  const adsSpeed = 1 / (weapon.adsTime || 0.2);
  view.adsK = clamp(view.adsK + (adsWant ? adsSpeed : -adsSpeed) * dt, 0, 1);
  view.adsEase = easeInOutCubic(view.adsK);
  view.scoped = !!weapon.scope && view.adsEase > 0.55;

  if (view.scoped && opts.shiftDown && !view.breathLock && view.breath <= 0) {
    view.breath = BREATH_TIME;
    view.breathHeld = true;
  }
  if (!opts.shiftDown) view.breathLock = false;
  if (view.breath > 0) {
    view.breath -= dt;
    if (!opts.shiftDown || !view.scoped) {
      view.breath = 0;
      view.breathHeld = false;
    } else if (view.breath <= 0) {
      view.breathHeld = false;
      view.breathLock = true;
    }
  } else view.breathHeld = false;

  view.swayT += dt;
  view.swayAmp = damp(view.swayAmp, view.breathHeld ? 0.04 : 1, view.breathHeld ? 9 : 3.4, dt);

  view.sensScale = lerp(
    1,
    weapon.bracedAim
      ? 1
      : clamp(Math.tan((weapon.adsFov * PI) / 360) / Math.tan((baseFov * PI) / 360), 0.18, 1),
    view.adsEase
  );
}

/** Single-player bob, footsteps and camera pose. */
function stepView(
  dt: number,
  view: ViewState,
  loco: LocoState,
  weapon: ViewWeapon,
  walkSpeed: number,
  baseFov: number,
  nowSec: number,
  keys: { left: boolean; right: boolean },
  jug = false
): ViewPose {
  const hSpeed = Math.hypot(loco.vel.x, loco.vel.z);
  const moving = hSpeed > 0.6 && loco.onGround;
  view.bobAmp = damp(view.bobAmp, moving ? clamp(hSpeed / walkSpeed, 0, 1.5) : 0, 9, dt);
  let footstep: ViewPose['footstep'] = null;
  if (moving) {
    const prev = view.stepPhase;
    view.stepPhase += dt * hSpeed * (jug ? 0.92 : loco.prone ? 0.72 : loco.crouch ? 1.05 : 1.42);
    if (Math.floor(prev / PI) !== Math.floor(view.stepPhase / PI)) {
      const vol = jug ? 1.25 : loco.prone ? 0.18 : loco.crouch ? 0.35 : loco.sprint ? 1.15 : 0.8;
      footstep = { vol, pan: clamp(Math.sin(view.stepPhase) * 0.35, -1, 1) };
    }
  }

  view.shake = damp(view.shake, 0, 7.5, dt);
  view.landShake = damp(view.landShake, 0, 9, dt);
  view.eye = damp(view.eye, loco.height * 0.92, 16, dt);
  view.fovKick = damp(view.fovKick, 0, 13, dt);

  const bobY = Math.sin(view.stepPhase * 2) * 0.032 * view.bobAmp;
  const bobX = Math.sin(view.stepPhase) * 0.036 * view.bobAmp;
  const bobR = Math.sin(view.stepPhase) * 0.01 * view.bobAmp;
  const shk = view.shake;
  const sX =
    (Math.sin(nowSec * 57.3 + view.shakeSeed) + Math.sin(nowSec * 31.1)) * 0.5 * shk * 0.03;
  const sY =
    (Math.sin(nowSec * 43.7 + view.shakeSeed * 2) + Math.sin(nowSec * 67.3)) * 0.5 * shk * 0.03;
  const sR = Math.sin(nowSec * 39.9 + view.shakeSeed * 3) * shk * 0.016;
  const steady = 1 - 0.82 * view.adsEase;
  const stance = loco.prone ? 0.45 : loco.crouch ? 0.72 : 1;
  view.scopeSwayX = 0;
  view.scopeSwayY = 0;
  if (weapon.scope && view.adsEase > 0.02) {
    const a = 0.0125 * view.adsEase * view.swayAmp * stance;
    view.scopeSwayX = Math.sin(view.swayT * 0.62) * a + Math.sin(view.swayT * 1.13 + 1.7) * a * 0.3;
    view.scopeSwayY =
      Math.sin(view.swayT * 0.47 + 2.2) * a * 0.72 + Math.sin(view.swayT * 0.91) * a * 0.22;
  }

  const hipTarget = jug
    ? 68
    : baseFov + (loco.sprint && hSpeed > 4.5 ? 7.5 : 0) + clamp(hSpeed - 5, 0, 3) * 0.6;
  view.hipFov = damp(view.hipFov, hipTarget, 7, dt);
  const aimFov = weapon.bracedAim ? view.hipFov : weapon.adsFov;
  view.fov = lerp(view.hipFov, aimFov, view.adsEase) + view.fovKick * (1 - view.adsEase * 0.75);

  return {
    x: loco.pos.x + (bobX * 0.4 + sX) * steady,
    y: loco.pos.y + view.eye + (bobY + sY) * steady - view.landShake * 0.16,
    z: loco.pos.z + sX * 0.5 * steady,
    pitch:
      view.pitch +
      view.recoilPitch -
      view.landShake * 0.1 -
      (loco.mantleTilt || 0) +
      sY * 0.6 * steady +
      view.scopeSwayY,
    yaw: view.yaw + view.recoilYaw + view.scopeSwayX,
    roll: (bobR + sR) * steady + ((keys.left ? 0.014 : 0) - (keys.right ? 0.014 : 0)) * steady,
    fov: view.fov,
    footstep,
  };
}

/** Single-player look + feet + camera, in that order. Hosts only bind world/input. */
function stepPlayer(
  dt: number,
  view: ViewState,
  loco: LocoState,
  weapon: ViewWeapon,
  lookOpts: { shiftDown: boolean; reloading: boolean; switching: boolean; dead?: boolean },
  mouseSens: number,
  baseFov: number,
  input: LocoInput,
  world: WorldQuery,
  movement: MovementTuning,
  walkSpeed: number,
  nowSec: number,
  lean: { left: boolean; right: boolean },
  events: LocoEvents,
  jug = false
): ViewPose {
  stepLook(dt, view, weapon, lookOpts, mouseSens, baseFov);
  loco.yaw = view.yaw;
  loco.ads = view.ads;
  loco.adsEase = view.adsEase;
  stepLocomotion(dt, loco, input, world, movement, events);
  return stepView(dt, view, loco, weapon, walkSpeed, baseFov, nowSec, lean, jug);
}


/* ==== shared/gameplay/reload.ts ==== */

interface ReloadState {
  progress: number;
  duration: number;
  empty: boolean;
  rounds: number;
  phase: number;
  magOut: boolean;
  inserted: boolean;
  actionDone: boolean;
  magVisualReleased: boolean;
  active: boolean;
  soundLift: boolean;
  soundOut: boolean;
  soundIn: boolean;
  soundAction: boolean;
}

interface ReloadWeapon {
  id: string;
  mag: number;
  reserve: number;
  magSize: number;
  reloadTime: number;
  tacticalReloadTime: number;
  reloadState: ReloadState | null;
}

interface ReloadClock {
  reloadT: number;
  reloadDuration: number;
  reloadEmpty: boolean;
  reloadRounds: number;
  reloadPhase: number;
}

type ReloadStageName = 'lift' | 'out' | 'in' | 'action';

interface ReloadHooks {
  onHud?: () => void;
  onSound?: (family: string, stage: ReloadStageName) => void;
}

const RELOAD_STAGE: Record<string, { remove: number; insert: number; action: number }> = {
  rifle: { remove: 0.055, insert: 0.7, action: 0.83 },
  ak: { remove: 0.3, insert: 0.72, action: 0.91 },
  pistol: { remove: 0.28, insert: 0.66, action: 0.9 },
  sniper: { remove: 0.34, insert: 0.86, action: 0.98 },
  lmg: { remove: 0.42, insert: 0.72, action: 0.96 },
  vector: { remove: 0.28, insert: 0.68, action: 0.9 },
  p90: { remove: 0.31, insert: 0.72, action: 0.91 },
};

function reloadCapacity(w: ReloadWeapon, empty: boolean) {
  return isShotgun(w.id) ? w.magSize : w.magSize + (empty ? 0 : 1);
}

function makeReloadState(w: ReloadWeapon): ReloadState {
  const empty = w.mag <= 0;
  const rounds = Math.min(reloadCapacity(w, empty) - w.mag, w.reserve);
  const duration = isShotgun(w.id)
    ? 0.46 + rounds * 0.42 + (empty ? 0.18 : 0)
    : empty
      ? w.reloadTime
      : w.tacticalReloadTime || w.reloadTime * 0.78;
  return {
    progress: 0,
    duration,
    empty,
    rounds,
    phase: 0,
    magOut: false,
    inserted: false,
    actionDone: false,
    magVisualReleased: false,
    active: false,
    soundLift: false,
    soundOut: false,
    soundIn: false,
    soundAction: false,
  };
}

function restore(clock: ReloadClock, state: ReloadState) {
  clock.reloadDuration = state.duration;
  clock.reloadT = Math.max(0.001, state.duration * (1 - state.progress));
  clock.reloadEmpty = state.empty;
  clock.reloadRounds = state.rounds;
  clock.reloadPhase = state.phase;
  state.active = true;
}

function startReload(
  w: ReloadWeapon,
  clock: ReloadClock,
  busy: boolean,
  hooks: ReloadHooks = {}
) {
  if (busy || clock.reloadT > 0) return false;
  if (w.reloadState) {
    restore(clock, w.reloadState);
    hooks.onHud?.();
    return true;
  }
  if (w.mag >= w.magSize || w.reserve <= 0) return false;
  w.reloadState = makeReloadState(w);
  restore(clock, w.reloadState);
  if (!w.reloadState.soundLift) {
    w.reloadState.soundLift = true;
    hooks.onSound?.(weaponFamily(w.id), 'lift');
  }
  hooks.onHud?.();
  return true;
}

function interruptReload(w: ReloadWeapon | null, clock: ReloadClock) {
  if (clock.reloadT <= 0) return;
  const state = w?.reloadState;
  if (state) {
    state.progress = Math.max(
      state.progress,
      clamp(1 - clock.reloadT / Math.max(0.001, clock.reloadDuration), 0, 0.999)
    );
    state.phase = clock.reloadPhase;
    state.active = false;
  }
  clock.reloadT = 0;
  clock.reloadDuration = 0;
  clock.reloadEmpty = false;
  clock.reloadRounds = 0;
  clock.reloadPhase = 0;
}

function seatMagazine(w: ReloadWeapon, state: ReloadState, clock: ReloadClock, hooks: ReloadHooks) {
  if (state.inserted) return;
  const take = Math.min(Math.max(0, reloadCapacity(w, state.empty) - w.mag), w.reserve);
  w.mag += take;
  w.reserve -= take;
  state.inserted = true;
  if (!state.soundIn) {
    state.soundIn = true;
    hooks.onSound?.(weaponFamily(w.id), 'in');
  }
  hooks.onHud?.();
}

function loadShotgunRounds(
  w: ReloadWeapon,
  state: ReloadState,
  clock: ReloadClock,
  desired: number,
  hooks: ReloadHooks
) {
  while (state.phase < desired && state.phase < state.rounds && w.reserve > 0) {
    if (w.mag >= w.magSize) break;
    w.mag++;
    w.reserve--;
    state.phase++;
    clock.reloadPhase = state.phase;
    hooks.onSound?.('shotgun', 'in');
  }
  hooks.onHud?.();
}

function finishReload(w: ReloadWeapon, clock: ReloadClock, hooks: ReloadHooks = {}) {
  const state = w.reloadState;
  if (state) {
    if (isShotgun(w.id)) loadShotgunRounds(w, state, clock, state.rounds, hooks);
    else seatMagazine(w, state, clock, hooks);
    state.actionDone = true;
    w.reloadState = null;
  }
  clock.reloadT = 0;
  clock.reloadDuration = 0;
  clock.reloadEmpty = false;
  clock.reloadRounds = 0;
  clock.reloadPhase = 0;
  hooks.onHud?.();
}

function updateReload(
  dt: number,
  w: ReloadWeapon,
  clock: ReloadClock,
  hooks: ReloadHooks = {}
) {
  const state = w.reloadState;
  if (!state) {
    clock.reloadT = 0;
    return;
  }
  clock.reloadT = Math.max(0, clock.reloadT - dt);
  state.progress = clamp(1 - clock.reloadT / state.duration, 0, 1);
  if (isShotgun(w.id)) {
    const elapsed = state.progress * state.duration;
    const desired = clamp(Math.floor((elapsed - 0.2) / 0.42) + 1, 0, state.rounds);
    loadShotgunRounds(w, state, clock, desired, hooks);
    if (state.empty && elapsed >= 0.2 + state.rounds * 0.42 && !state.soundAction) {
      state.soundAction = true;
      hooks.onSound?.('shotgun', 'action');
    }
  } else {
    const marks = RELOAD_STAGE[weaponFamily(w.id)] || { remove: 0.32, insert: 0.68, action: 0.9 };
    if (state.progress >= marks.remove) {
      state.magOut = true;
      if (!state.soundOut) {
        state.soundOut = true;
        hooks.onSound?.(weaponFamily(w.id), 'out');
      }
    }
    if (state.progress >= marks.insert) seatMagazine(w, state, clock, hooks);
    if (state.progress >= marks.action && !state.actionDone) {
      state.actionDone = true;
      if (state.empty && !state.soundAction) {
        state.soundAction = true;
        hooks.onSound?.(weaponFamily(w.id), 'action');
      }
    }
  }
  if (clock.reloadT <= 0) finishReload(w, clock, hooks);
}

function reloadBlocksFire(
  w: ReloadWeapon,
  clock: ReloadClock,
  busy: boolean,
  hooks: ReloadHooks
) {
  const state = w.reloadState;
  if (!state || state.active || isShotgun(w.id)) return false;
  const open = !state.inserted || (state.empty && !state.actionDone);
  if (open) startReload(w, clock, busy, hooks);
  return open;
}

function interruptShotgunReloadForFire(w: ReloadWeapon, clock: ReloadClock) {
  if (!isShotgun(w.id) || clock.reloadT <= 0 || w.mag <= 0) return false;
  interruptReload(w, clock);
  w.reloadState = null;
  return true;
}

function discardReloadCheckpoint(w: ReloadWeapon) {
  if (w.reloadState?.active) return;
  w.reloadState = null;
}


/* ==== shared/gameplay/fire.ts ==== */

interface FireWeapon {
  id: string;
  auto: boolean;
  semi: boolean;
  mag: number;
  reserve: number;
  rpm: number;
  pumpTime?: number;
  boltTime?: number;
  spread: number;
  spreadMax: number;
  spreadShot: number;
}

type FireKind = 'blocked' | 'dry' | 'reload' | 'fired';

interface FireResult {
  kind: FireKind;
  pump?: boolean;
  bolt?: boolean;
  emptyAutoReload?: boolean;
}

function isFullAuto(w: FireWeapon) {
  return w.auto && !w.semi;
}

function tryConsumeShot(
  w: FireWeapon,
  triggerReleased: boolean,
  blocked: boolean
): FireResult {
  if (blocked) return { kind: 'blocked' };
  if (!isFullAuto(w) && !triggerReleased) return { kind: 'blocked' };
  if (w.mag <= 0) {
    if (triggerReleased && w.reserve > 0) return { kind: 'reload' };
    return { kind: 'dry' };
  }
  w.mag--;
  w.spread = Math.min(w.spreadMax, w.spread + w.spreadShot);
  const family = weaponFamily(w.id);
  if (isShotgun(w.id)) return { kind: 'fired', pump: true };
  if (family === 'sniper') return { kind: 'fired', bolt: true };
  if (w.mag === 0) return { kind: 'fired', emptyAutoReload: true };
  return { kind: 'fired' };
}

function fireInterval(rpm: number) {
  return 60 / Math.max(1, rpm);
}

const SPRINT_FIRE_RAISE = 0.11;


/* ==== shared/gameplay/melee.ts ==== */
const MELEE_RANGE = 2.35;
const MELEE_DURATION = 0.46;
const MELEE_BODY_DAMAGE = 65;
const MELEE_HEAD_DAMAGE = 100;

interface MeleeBusy {
  dead?: boolean;
  meleeT: number;
  switching: boolean;
  blocked?: boolean;
}

function canStartMelee(busy: MeleeBusy) {
  return !busy.dead && busy.meleeT <= 0 && !busy.switching && !busy.blocked;
}

function meleeDamage(head: boolean) {
  return head ? MELEE_HEAD_DAMAGE : MELEE_BODY_DAMAGE;
}

function beginMeleeClock() {
  return { meleeT: MELEE_DURATION, fireLock: MELEE_DURATION };
}


/* ==== shared/gameplay/ai.ts ==== */

const ENEMY_SIGHT = 52;
const ENEMY_HP = 100;
const ENEMY_REACTION_MIN = 0.3;
const ENEMY_REACTION_MAX = 0.8;
const ENEMY_BURST_GAP = [0.11, 0.15] as const;
const ENEMY_BURST_REST = [0.85, 1.9] as const;

type EnemyTactic = 'hold' | 'flank' | 'push';
type EnemyPhase = 'patrol' | 'alert' | 'combat';

function rollEnemyTactic(rng = Math.random): EnemyTactic {
  const r = rng();
  return r < 0.42 ? 'hold' : r < 0.72 ? 'flank' : 'push';
}

function enemyPlayerDamage(dist: number, rng = Math.random) {
  return (5.5 + rng() * 3.5) * clamp(1 - Math.max(0, dist - 25) / 55, 0.5, 1);
}

function nextReactionDelay(rng = Math.random) {
  return ENEMY_REACTION_MIN + rng() * (ENEMY_REACTION_MAX - ENEMY_REACTION_MIN);
}

function nextBurstCount(rng = Math.random) {
  return randI(2, 4);
}

function combatSteer(
  dist: number,
  tactic: EnemyTactic,
  strafeDir: number,
  dx: number,
  dz: number
) {
  const inv = 1 / (dist || 1);
  const fx = dx * inv;
  const fz = dz * inv;
  const sx = -fz * strafeDir;
  const sz = fx * strafeDir;
  if (tactic === 'flank') {
    const closeness = clamp((dist - 12) / 9, -1, 1);
    return { mx: sx + fx * closeness * 0.5, mz: sz + fz * closeness * 0.5, speed: 3.5 };
  }
  if (tactic === 'push') {
    const closeness = clamp((dist - 8.5) / 7, -1, 1);
    return {
      mx: sx * 0.55 + fx * closeness * 1.1,
      mz: sz * 0.55 + fz * closeness * 1.1,
      speed: 3.3,
    };
  }
  return { mx: sx * 0.85, mz: sz * 0.85, speed: 2.5 };
}

/** Single-player unalerted cone: forward · toTarget >= 0.2. Alerted skips FOV. */
function inEnemyFov(
  forwardX: number,
  forwardZ: number,
  toX: number,
  toZ: number,
  alerted: boolean
) {
  if (alerted) return true;
  const fl = Math.hypot(forwardX, forwardZ) || 1;
  const tl = Math.hypot(toX, toZ) || 1;
  return (forwardX * toX + forwardZ * toZ) / (fl * tl) >= 0.2;
}

function patrolOffset(t: number, baseX: number, baseZ: number, scale = 1) {
  return {
    x: baseX + Math.sin(t * 0.55) * 2.4 * scale,
    z: baseZ + Math.cos(t * 0.4) * 1.8 * scale,
  };
}

function burstGap(continuing: boolean, rng = Math.random) {
  return continuing
    ? rand(ENEMY_BURST_GAP[0], ENEMY_BURST_GAP[1])
    : rand(ENEMY_BURST_REST[0], ENEMY_BURST_REST[1]);
}


/* ==== shared/gameplay/throwables.ts ==== */

type ThrowableKind = 'lethal' | 'tactical';

const THROW_SPEED = 13;
const THROW_LIFT = 5.5;
const THROW_GRAVITY = 12;
const THROW_LIFE = 4;
const THROWABLE_MAX = 3;
const THROWABLE_START_LETHAL = 1;
const THROWABLE_START_TACTICAL = 1;
const LETHAL_ENEMY_RADIUS = 6.5;
const LETHAL_PLAYER_RADIUS = 5;

interface ThrowInventory {
  lethals: number;
  tacticals: number;
  max: number;
}

interface FlyingThrow {
  kind: ThrowableKind;
  x: number;
  y: number;
  z: number;
  vx: number;
  vy: number;
  vz: number;
  life: number;
}

function createThrowInventory(
  lethals = THROWABLE_START_LETHAL,
  tacticals = THROWABLE_START_TACTICAL,
  max = THROWABLE_MAX
): ThrowInventory {
  return { lethals, tacticals, max };
}

function canThrow(inv: ThrowInventory, kind: ThrowableKind) {
  return kind === 'lethal' ? inv.lethals > 0 : inv.tacticals > 0;
}

function consumeThrow(inv: ThrowInventory, kind: ThrowableKind) {
  if (!canThrow(inv, kind)) return false;
  if (kind === 'lethal') inv.lethals--;
  else inv.tacticals--;
  return true;
}

function addThrowables(inv: ThrowInventory, amount = 1) {
  inv.lethals = Math.min(inv.max, inv.lethals + amount);
  inv.tacticals = Math.min(inv.max, inv.tacticals + amount);
}

function spawnThrow(
  kind: ThrowableKind,
  ox: number,
  oy: number,
  oz: number,
  dx: number,
  dy: number,
  dz: number
): FlyingThrow {
  const len = Math.hypot(dx, dy, dz) || 1;
  return {
    kind,
    x: ox + (dx / len) * 0.7,
    y: oy + (dy / len) * 0.7 - 0.2,
    z: oz + (dz / len) * 0.7,
    vx: (dx / len) * THROW_SPEED,
    vy: (dy / len) * THROW_SPEED + THROW_LIFT,
    vz: (dz / len) * THROW_SPEED,
    life: THROW_LIFE,
  };
}

function stepThrow(t: FlyingThrow, dt: number, groundY: number): 'flying' | 'detonate' {
  t.life -= dt;
  t.vy -= THROW_GRAVITY * dt;
  t.x += t.vx * dt;
  t.y += t.vy * dt;
  t.z += t.vz * dt;
  if (t.life <= 0 || t.y <= groundY + 0.06) return 'detonate';
  return 'flying';
}

function lethalEnemyDamage(dist: number) {
  if (dist >= LETHAL_ENEMY_RADIUS) return 0;
  return 400 * clamp(1 - dist / 8, 0.35, 1);
}

function lethalPlayerDamage(dist: number) {
  if (dist >= LETHAL_PLAYER_RADIUS) return 0;
  return 60 * clamp(1 - dist / 6, 0.3, 1);
}


/* ==== shared/gameplay/loot.ts ==== */
/** Enemy drops, ground ammo, and F-to-swap. Both shooters import this. */

type LootKind = 'weapon' | 'ammo' | 'lootWeapon';

const LOOT_WEAPON_RANGE = 2.4;
const LOOT_AMMO_RANGE = 2.2;
const ENEMY_DROP_WEAPON_CHANCE = 0.55;
const ENEMY_DROP_WEAPON_POOL = ['ak12', 'p90'] as const;
const AMMO_PICKUP_AMOUNT = 60;
const AMMO_PICKUP_COOLDOWN_MS = 15000;

interface LootQuery {
  kind: LootKind;
  x: number;
  z: number;
  coolUntil: number;
  weaponId?: string;
}

function ammoLootLabel(fromEnemy: boolean) {
  return fromEnemy ? '敌人弹药' : '弹药补给';
}

function weaponLootLabel(name: string, replace: boolean, slot = 2) {
  return `F ${replace ? '替换' : '拾取'} 主武器 ${slot} — ${name}`;
}

function nearestWeaponLootIndex(items: LootQuery[], px: number, pz: number, now: number) {
  let best = -1;
  let bestD = LOOT_WEAPON_RANGE;
  for (let i = 0; i < items.length; i++) {
    const p = items[i];
    if (p.kind === 'ammo' || p.coolUntil > now || !p.weaponId) continue;
    const d = Math.hypot(p.x - px, p.z - pz);
    if (d < bestD) {
      bestD = d;
      best = i;
    }
  }
  return best;
}

function shouldAutoPickupAmmo(dist: number, coolUntil: number, now: number) {
  return dist < LOOT_AMMO_RANGE && coolUntil <= now;
}

function nextAmmoCooldown(now: number) {
  return now + AMMO_PICKUP_COOLDOWN_MS;
}

function rollEnemyDrops(rng = Math.random): { ammo: boolean; weaponId: string | null } {
  const weaponId =
    rng() < ENEMY_DROP_WEAPON_CHANCE
      ? ENEMY_DROP_WEAPON_POOL[(rng() * ENEMY_DROP_WEAPON_POOL.length) | 0]
      : null;
  return { ammo: true, weaponId };
}

/** Swap the ground gun with whatever is in the active slot. */
function interactGroundWeapon(
  groundWeaponId: string,
  currentWeaponId: string | null
): { take: string; leave: string | null } {
  return { take: groundWeaponId, leave: currentWeaponId };
}


/* ==== shared/gameplay/crosshair.ts ==== */

const CROSSHAIR = {
  inGap: 1,
  inLen: 4,
  inThick: 2,
  outGap: 2,
  outLen: 3,
  outThick: 2,
  outline: 1,
  maxSpread: 12,
  baseScale: 105,
  reloadErr: 2.0,
  fireScale: 240,
  fireHold: 0.11,
  fallRate: 20,
};

function crosshairCanvasSize() {
  return (
    2 * Math.ceil(CROSSHAIR.inGap + CROSSHAIR.maxSpread + CROSSHAIR.inLen + CROSSHAIR.outline) + 8
  );
}

function crosshairTarget(state: {
  baseSpread: number;
  moveSpread: number;
  speed: number;
  airSpread: number;
  stanceSpread: number;
  adsEase: number;
  reloading: boolean;
  firing: boolean;
  spread: number;
}) {
  let target =
    (state.baseSpread + (state.speed / 7) * state.moveSpread + state.airSpread) *
    CROSSHAIR.baseScale *
    state.stanceSpread;
  if (state.reloading) target += CROSSHAIR.reloadErr;
  if (state.firing)
    target += (state.spread - state.baseSpread) * CROSSHAIR.fireScale * state.stanceSpread;
  target *= 1 - 0.45 * state.adsEase;
  return clamp(target, 0, CROSSHAIR.maxSpread);
}

function stepCrosshairSpread(current: number, target: number, dt: number) {
  return target > current ? target : damp(current, target, CROSSHAIR.fallRate, dt);
}

function adsHidesCrosshair(adsEase: number, bracedAim: boolean) {
  return adsEase > 0.12 && !bracedAim;
}

function scopeBlend(adsEase: number, hasScope: boolean) {
  return hasScope ? clamp((adsEase - 0.45) / 0.4, 0, 1) : 0;
}

function showBreathHint(
  scopeK: number,
  breathLock: boolean,
  breath: number,
  breathHeld: boolean
) {
  return scopeK > 0.5 && !breathLock && breath <= 0 && !breathHeld;
}

function drawCrosshair(
  ctx: {
    clearRect: (x: number, y: number, w: number, h: number) => void;
    fillRect: (x: number, y: number, w: number, h: number) => void;
    fillStyle: unknown;
  },
  layout: { dpr: number; cx: number; cy: number; width: number; height: number },
  iA: number
) {
  ctx.clearRect(0, 0, layout.width, layout.height);
  const d = layout.dpr;
  const u = (v: number) => Math.max(1, Math.round(v * d));
  const o = Math.max(1, Math.round(CROSSHAIR.outline * d));
  const oA = Math.round((CROSSHAIR.inGap + CROSSHAIR.inLen + CROSSHAIR.outGap) * d);
  const arms = [
    [iA, u(CROSSHAIR.inLen), u(CROSSHAIR.inThick), 0],
    [oA, u(CROSSHAIR.outLen), u(CROSSHAIR.outThick), 1],
  ];
  for (let pass = 0; pass < 2; pass++) {
    ctx.fillStyle = pass ? 'rgba(255,255,255,.97)' : 'rgba(0,0,0,.88)';
    const kf = pass ? 0 : o;
    for (const [a, len, t, near] of arms) {
      const kn = pass ? 0 : o * near;
      const thin = t + (pass ? 0 : 2 * o);
      const long = len + kf + kn;
      const off = (t >> 1) + (pass ? 0 : o);
      ctx.fillRect(layout.cx - off, layout.cy - a - len - kf, thin, long);
      ctx.fillRect(layout.cx - off, layout.cy + a - kn, thin, long);
      ctx.fillRect(layout.cx - a - len - kf, layout.cy - off, long, thin);
      ctx.fillRect(layout.cx + a - kn, layout.cy - off, long, thin);
    }
  }
}


/* ==== shared/gameplay/combat-fx.ts ==== */
/** Combat FX numbers from single-player tracers / shells / death guns. */

const SPARK_LIFE = 0.07;
const SHELL_LIFE = 0.9;
const SHELL_GRAVITY = 17;
const SHELL_FLOOR = 0.04;
const TRACER_SPEED = 285;
const TRACER_SPEED_SNIPER = 430;
const TRACER_SEGMENT = 3.4;
const TRACER_SEGMENT_SNIPER = 5.2;

interface TracerFlight {
  length: number;
  segment: number;
  speed: number;
  lead: number;
  fresh: boolean;
}

function createTracerFlight(length: number, sniper: boolean): TracerFlight {
  const segment = sniper ? TRACER_SEGMENT_SNIPER : TRACER_SEGMENT;
  return {
    length,
    segment,
    speed: sniper ? TRACER_SPEED_SNIPER : TRACER_SPEED,
    lead: Math.min(length, segment),
    fresh: true,
  };
}

function stepTracerFlight(tr: TracerFlight, dt: number) {
  if (tr.fresh) {
    tr.fresh = false;
    return { tail: 0, head: tr.lead, done: false, opacity: 0.95, scale: 1 };
  }
  tr.lead += tr.speed * dt;
  const tail = Math.max(0, tr.lead - tr.segment);
  if (tail >= tr.length) return { tail, head: tr.length, done: true, opacity: 0, scale: 1 };
  const head = Math.min(tr.length, tr.lead);
  const visible = Math.max(0, head - tail);
  const k = Math.min(1, visible / Math.min(tr.segment, tr.length));
  return { tail, head, done: false, opacity: k * 0.95, scale: 0.45 + k * 0.55 };
}

function shellImpulse(rightX: number, rightZ: number, rng = Math.random) {
  return {
    vx: rightX * 2.2 + (rng() - 0.5) * 0.5,
    vy: 1.5 + rng() * 0.6,
    vz: rightZ * 2.2 + (rng() - 0.5) * 0.5,
    avx: 12,
    avy: 8,
    avz: 10,
    life: SHELL_LIFE,
  };
}

function stepShellBody(
  s: { x: number; y: number; z: number; vx: number; vy: number; vz: number; life: number },
  dt: number,
  floorY = SHELL_FLOOR
) {
  s.life -= dt;
  s.vy -= SHELL_GRAVITY * dt;
  s.x += s.vx * dt;
  s.y += s.vy * dt;
  s.z += s.vz * dt;
  let bounced = false;
  if (s.y < floorY) {
    s.y = floorY;
    s.vy *= -0.25;
    s.vx *= 0.5;
    s.vz *= 0.5;
    bounced = true;
  }
  return { dead: s.life <= 0, bounced };
}


/* ==== shared/gameplay/death.ts ==== */

const DEATH_DURATION = 0.85;
const DEATH_GUN_DROP_AT = 0.14;
const DEATH_GUN_GRAVITY = 17;
const DEATH_GUN_FLOOR = 0.07;

interface DeathBody {
  deathT: number;
  modelRotX: number;
  modelPosY: number;
  modelRotZ: number;
  dropGun: boolean;
  done: boolean;
}

function stepDeathBody(deathT: number, dt: number): DeathBody {
  const next = Math.min(1, deathT + dt / DEATH_DURATION);
  const k = easeOutCubic(next);
  return {
    deathT: next,
    modelRotX: k * Math.PI * 0.5 * 0.98,
    modelPosY: -k * 0.1,
    modelRotZ: Math.sin(next * 4) * 0.08 * (1 - k),
    dropGun: next > DEATH_GUN_DROP_AT,
    done: next >= 1,
  };
}

function deathLimbTargets(index: number, kind: 'leg' | 'arm') {
  if (kind === 'leg') {
    return { hipX: index ? 0.3 : -0.25, kneeX: 0.55, shX: 0, shZ: 0, elX: 0 };
  }
  return {
    hipX: 0,
    kneeX: 0,
    shX: index ? 0.6 : 0.35,
    shZ: (index ? 1 : -1) * 0.5,
    elX: 0.2,
  };
}

function blendDeathLimb(cur: number, tgt: number, dt: number) {
  return lerp(cur, tgt, Math.min(1, dt * 6));
}

function deathGunImpulse(rng = Math.random) {
  return {
    vx: rand(-1.6, 1.6),
    vy: rand(0.6, 1.8),
    vz: rand(-1.6, 1.6),
    avx: rand(-6, 6),
    avy: rand(-6, 6),
    avz: rand(-6, 6),
  };
}

function stepDeathGun(
  g: {
    x: number;
    y: number;
    z: number;
    vx: number;
    vy: number;
    vz: number;
    avx: number;
    avy: number;
    avz: number;
  },
  dt: number
) {
  g.vy -= DEATH_GUN_GRAVITY * dt;
  g.x += g.vx * dt;
  g.y += g.vy * dt;
  g.z += g.vz * dt;
  let bounced = false;
  let settled = false;
  if (g.y <= DEATH_GUN_FLOOR) {
    g.y = DEATH_GUN_FLOOR;
    if (Math.abs(g.vy) < 0.7) settled = true;
    else {
      g.vy *= -0.32;
      g.vx *= 0.55;
      g.vz *= 0.55;
      g.avx *= 0.5;
      g.avy *= 0.5;
      g.avz *= 0.5;
      bounced = true;
    }
  }
  return { settled, bounced };
}

function deathGunRestRotation(rng = Math.random) {
  return { x: rand(-0.1, 0.1), y: rand(0, 7), z: Math.PI / 2 + rand(-0.3, 0.3) };
}


/* ==== shared/gameplay/hurt-feedback.ts ==== */

/** World bearing of a hit, relative to view forward. Same as single-player arcs. */
function damageBearing(
  fromX: number,
  fromZ: number,
  camX: number,
  camZ: number,
  yaw: number
) {
  return Math.atan2(fromX - camX, fromZ - camZ) - (yaw + PI);
}

function damageFlashAmount(amount: number) {
  return Math.min(0.72, clamp(amount / 30, 0.22, 0.55));
}

function damageShakeAmount(amount: number) {
  return clamp(amount / 24, 0.18, 0.6);
}

function lowHealthPulse(hp: number, timeMs: number, pulse: number) {
  if (hp >= 20 || hp <= 0) return 0;
  return pulse * (0.55 + 0.45 * Math.sin(timeMs * 0.006));
}


/* ==== shared/gameplay/attachments.ts ==== */
const ATTACHMENT_CATALOG = {
  optic: {
    micro_dot: { name: '微型红点', mods: { adsTime: 0.96 } },
    holo: { name: '方窗全息瞄具', mods: { adsTime: 0.99 } },
    prism_2_5: { name: '2.5× 棱镜镜', mods: { adsTime: 1.14, adsFov: 0.895 } },
  },
  muzzle: {
    compensator: {
      name: '战术制退器',
      mods: { recoilKick: 0.9, recoilRot: 0.9, camPitch: 0.88, camYaw: 0.82, noise: 1.08 },
    },
    suppressor: {
      name: '快拆消音器',
      mods: { noise: 0.62, range: 0.92, recoilKick: 0.96, camPitch: 0.96 },
    },
  },
  underbarrel: {
    angled_grip: { name: '斜角握把', mods: { adsTime: 0.91, moveSpread: 0.9 } },
    vertical_grip: {
      name: '垂直握把',
      mods: { recoilKick: 0.86, recoilRot: 0.78, camPitch: 0.78, camYaw: 0.7, spreadShot: 0.88 },
    },
  },
  magazine: {
    standard: { name: '标准弹匣', mods: {} },
    extended: {
      name: '扩容弹匣',
      mods: { magSize: 1.33, reloadTime: 1.12, tacticalReloadTime: 1.12 },
    },
  },
} as const;

function campaignStartAttachments(weaponId: string): Record<string, string> {
  if (weaponId === 'm4' || weaponId === 'rifle') {
    return {
      optic: 'micro_dot',
      muzzle: 'suppressor',
      underbarrel: 'vertical_grip',
      magazine: 'extended',
    };
  }
  if (weaponId === 'p9' || weaponId === 'pistol') return { muzzle: 'suppressor' };
  if (weaponId === 'ak' || weaponId === 'ak12') {
    return {
      optic: 'micro_dot',
      muzzle: 'compensator',
      underbarrel: 'angled_grip',
      magazine: 'standard',
    };
  }
  return {};
}

function applyAttachmentMods<T extends Record<string, unknown>>(
  base: T,
  attachments: Record<string, string>
): T {
  const out = { ...base };
  for (const [slot, id] of Object.entries(attachments)) {
    const spec = (
      ATTACHMENT_CATALOG as Record<string, Record<string, { mods: Record<string, number> }>>
    )[slot]?.[id];
    if (!spec) continue;
    for (const [stat, mul] of Object.entries(spec.mods)) {
      const cur = out[stat];
      if (typeof cur === 'number') (out as Record<string, unknown>)[stat] = cur * mul;
    }
  }
  if (typeof out.magSize === 'number')
    (out as Record<string, unknown>).magSize = Math.round(out.magSize as number);
  return out;
}

function isSuppressed(attachments?: Record<string, string> | null) {
  return attachments?.muzzle === 'suppressor';
}


/* ==== shared/gameplay/nameplate.ts ==== */
/** CoD-style plates: hidden until you aim at them, or just after you hit them. */
const NAMEPLATE_AIM_DOT = 0.986;
const NAMEPLATE_MAX_DIST = 46;
const NAMEPLATE_HIT_REVEAL = 1.25;

function nameplateVisible(started: boolean, dist: number, aimDot: number, revealT: number) {
  if (!started || dist > NAMEPLATE_MAX_DIST) return false;
  return revealT > 0 || aimDot >= NAMEPLATE_AIM_DOT;
}


/* ==== shared/gameplay/stealth.ts ==== */
/** Stealth sense for campaign infiltration. Combat after stealthUntilZ. */
const STEALTH_FAIL_HOLD = 1.15;

function sightDetectRate(opts: {
  dist: number;
  inFov: boolean;
  hasLos: boolean;
  crouched: boolean;
  prone: boolean;
  sprinting: boolean;
}) {
  if (!opts.hasLos) return -0.42;
  const range = opts.prone ? 13 : opts.crouched ? 21 : opts.sprinting ? 36 : 28;
  if (opts.dist > range + 6) return opts.inFov ? -0.12 : -0.28;
  if (!opts.inFov && opts.dist > 7) return -0.16;
  if (opts.dist > range) return opts.inFov ? 0.04 : -0.1;
  const closeness = 1 - opts.dist / range;
  let rate = 0.18 + closeness * 0.9;
  if (opts.prone) rate *= 0.32;
  else if (opts.crouched) rate *= 0.52;
  if (opts.sprinting) rate *= 1.5;
  if (!opts.inFov) rate *= 0.22;
  return rate;
}

function hearSpike(
  dist: number,
  sprinting: boolean,
  suppressedShot: boolean,
  loudShot: boolean
) {
  if (loudShot && dist < 44) return 1;
  if (suppressedShot && dist < 9) return 0.58;
  if (sprinting && dist < 10) return 0.2;
  return 0;
}

function stealthActive(playerZ: number, untilZ: number) {
  return playerZ > untilZ;
}


/* ==== shared/gameplay/mission-director.ts ==== */
/** Named 鹰落 beats. Campaign frame loop and tests call these same functions. */

const PATH_METERS = 2000;
const SPAWN_Z = 1000;
const EXIT_Z = -1000;
const STEALTH_UNTIL_Z = 500;
const VEGA_INTERACT_RANGE = 2.6;
const MODULE_INTERACT_RANGE = 2.4;
const FUEL_INTERACT_RANGE = 3.2;
const VEGA_MAX_HP = 100;
const APC_SPEED = 3.8;

type EnemyKind = 'rifle' | 'shotgun' | 'nco';
type InfilMode = 'stealth-or-combat' | 'combat';

const ZONES = {
  teach: { id: 'teach', minZ: 800, maxZ: 1000, label: '坠机残骸 A' },
  road: { id: 'road', minZ: 500, maxZ: 800, label: '林间旧伐木道' },
  crash: { id: 'crash', minZ: 200, maxZ: 500, label: '主坠机点' },
  valleyA: { id: 'valleyA', minZ: -100, maxZ: 200, label: '河谷 A' },
  fuel: { id: 'fuel', minZ: -400, maxZ: -100, label: '油料场' },
  valleyB: { id: 'valleyB', minZ: -750, maxZ: -400, label: '河谷 B' },
  bridge: { id: 'bridge', minZ: -1000, maxZ: -750, label: '公路桥' },
} as const;

type ZoneId = keyof typeof ZONES;

const RADIO = {
  wake: 'HAMMER：隼，听到请回答。保持隐蔽，夜视仪就位。',
  nvTeach: 'WEBER：按 N 开启夜视仪。蹲下再接近巡逻。',
  nvOn: 'WEBER：夜视已同步。伐木道上有两组搜索队，可潜行也可交火。',
  kit: 'HAMMER：装备点确认。消音 M4 继续前进。',
  road: 'HAMMER：旧伐木道。两队巡逻，别恋战。',
  crash: 'HAMMER：主残骸就在前方。找到 VEGA，拿回通讯模块。',
  vega: 'VEGA：我还能走。模块在货舱左侧，快拿。',
  module: 'WEBER：模块在线。沿河谷撤，北风会从三面压过来。',
  valley: 'HAMMER：追兵进河谷了，边打边撤，别回头固守。',
  fuel: 'HAMMER：油料场。炸罐，挡住后面的装甲。',
  fuelBlown: 'HAMMER：油罐炸了。追兵被切断，继续往桥走。',
  lightning: 'WEBER：雷击点燃树冠！主路封死，改走浅滩右侧。',
  apc: 'HAMMER：装甲车从桥北压过来，不可摧毁，在它到之前登车！',
  exfil: 'HAMMER：接应到了。上车！',
};

interface MissionApc {
  spawned: boolean;
  x: number;
  z: number;
  speed: number;
}

interface MissionState {
  flags: Record<string, boolean>;
  nvOn: boolean;
  nvTaught: boolean;
  vegaHp: number;
  vegaRescued: boolean;
  moduleTaken: boolean;
  fuelBlown: boolean;
  routeBlocked: boolean;
  apc: MissionApc;
  zone: ZoneId;
  radio: string;
  checkpointId: string;
}

function createMissionState(): MissionState {
  return {
    flags: {},
    nvOn: false,
    nvTaught: false,
    vegaHp: VEGA_MAX_HP,
    vegaRescued: false,
    moduleTaken: false,
    fuelBlown: false,
    routeBlocked: false,
    apc: { spawned: false, x: 0, z: -720, speed: APC_SPEED },
    zone: 'teach',
    radio: RADIO.wake,
    checkpointId: 'cp_spawn',
  };
}

function zoneAt(z: number): ZoneId {
  for (const id of Object.keys(ZONES) as ZoneId[]) {
    const zone = ZONES[id];
    if (z <= zone.maxZ && z > zone.minZ) return id;
  }
  return z > ZONES.teach.maxZ ? 'teach' : 'bridge';
}

function infiltrationMode(z: number): InfilMode {
  return z > STEALTH_UNTIL_Z ? 'stealth-or-combat' : 'combat';
}

function setFlag(state: MissionState, id: string) {
  if (state.flags[id]) return false;
  state.flags[id] = true;
  return true;
}

function toggleNightVision(state: MissionState) {
  state.nvOn = !state.nvOn;
  if (!state.nvTaught) {
    state.nvTaught = true;
    state.radio = RADIO.nvOn;
    setFlag(state, 'nvTaught');
  }
  return state.nvOn;
}

function teachNightVision(state: MissionState) {
  if (state.nvTaught) return false;
  state.radio = RADIO.nvTeach;
  return true;
}

function interactVega(state: MissionState, dist: number) {
  if (state.vegaRescued || state.vegaHp <= 0 || dist > VEGA_INTERACT_RANGE) return false;
  state.vegaRescued = true;
  state.radio = RADIO.vega;
  setFlag(state, 'vegaRescued');
  return true;
}

function takeCommsModule(state: MissionState, dist: number) {
  if (state.moduleTaken || dist > MODULE_INTERACT_RANGE) return false;
  state.moduleTaken = true;
  state.radio = RADIO.module;
  setFlag(state, 'moduleTaken');
  return true;
}

function hurtVega(state: MissionState, amount: number) {
  if (state.vegaRescued || state.vegaHp <= 0) return false;
  state.vegaHp = Math.max(0, state.vegaHp - amount);
  return state.vegaHp <= 0;
}

function tickVegaThreat(state: MissionState, nearbyHostile: boolean, dt: number) {
  if (!nearbyHostile) return false;
  return hurtVega(state, 16 * dt);
}

function triggerFuelBlast(state: MissionState, inFuelZone: boolean) {
  if (state.fuelBlown || !inFuelZone) return false;
  state.fuelBlown = true;
  state.radio = RADIO.fuelBlown;
  setFlag(state, 'fuelBlown');
  return true;
}

function triggerLightningReroute(state: MissionState, inValleyB: boolean) {
  if (state.routeBlocked || !inValleyB) return false;
  state.routeBlocked = true;
  state.radio = RADIO.lightning;
  setFlag(state, 'routeBlocked');
  return true;
}

function spawnApcPressure(state: MissionState, inBridge: boolean) {
  if (state.apc.spawned || !inBridge) return false;
  state.apc.spawned = true;
  state.apc.x = 0;
  state.apc.z = -720;
  state.apc.speed = APC_SPEED;
  state.radio = RADIO.apc;
  setFlag(state, 'apcSpawned');
  return true;
}

function stepApc(state: MissionState, dt: number, _playerZ: number) {
  if (!state.apc.spawned) return state.apc;
  // The BTR advances north along the road only. It is a time pressure from
  // behind, not a pet that mirrors the player's movement.
  state.apc.z -= state.apc.speed * dt;
  return state.apc;
}

function enterZone(state: MissionState, z: number) {
  const next = zoneAt(z);
  const changed = next !== state.zone;
  if (!changed) return { zone: next, entered: false, radio: state.radio };
  state.zone = next;
  const lines: Record<ZoneId, string> = {
    teach: RADIO.wake,
    road: RADIO.road,
    crash: RADIO.crash,
    valleyA: RADIO.valley,
    fuel: RADIO.fuel,
    valleyB: state.routeBlocked ? RADIO.lightning : RADIO.fuelBlown,
    bridge: RADIO.apc,
  };
  state.radio = lines[next];
  setFlag(state, `zone:${next}`);
  return { zone: next, entered: true, radio: state.radio };
}

function checkpointForZone(zone: ZoneId) {
  const map: Record<ZoneId, string> = {
    teach: 'cp_spawn',
    road: 'cp_road',
    crash: 'cp_crash',
    valleyA: 'cp_valley',
    fuel: 'cp_fuel',
    valleyB: 'cp_valleyB',
    bridge: 'cp_bridge',
  };
  return map[zone];
}

function restoreMissionStage(state: MissionState, checkpointId: string) {
  state.checkpointId = checkpointId;
  if (!state.vegaRescued || state.vegaHp <= 0) {
    state.vegaRescued = false;
    state.vegaHp = VEGA_MAX_HP;
    if (!state.flags.moduleTaken) state.moduleTaken = false;
  }
  return state;
}

function shouldResetLivingEnemy(_baseZ: number) {
  return true;
}

type RestoreEnemy = {
  alive: boolean;
  engaged: boolean;
  suspicion: number;
  lastSeenT: number;
  reactionT: number;
  baseX: number;
  baseZ: number;
  root?: { position: { x: number; z: number } };
};

function applyCheckpointRestore(
  state: MissionState,
  checkpointId: string,
  enemies: RestoreEnemy[]
) {
  restoreMissionStage(state, checkpointId);
  for (const e of enemies) {
    if (!e.alive || !shouldResetLivingEnemy(e.baseZ)) continue;
    e.engaged = false;
    e.suspicion = 0;
    e.lastSeenT = 0;
    e.reactionT = 0.55;
    if (e.root) {
      e.root.position.x = e.baseX;
      e.root.position.z = e.baseZ;
    }
  }
  return state;
}


  return {
    clamp,
    lerp,
    damp,
    easeOutCubic,
    easeInOutCubic,
    rand,
    randI,
    PI,
    weaponFamily,
    isShotgun,
    ballisticSurfaceFromKey,
    weaponPenetrationFor,
    damageFalloff,
    partMultiplier,
    tracePenetrations,
    LEG_MULTIPLIER,
    stanceSpreadMultiplier,
    stanceRecoilMultiplier,
    stanceRecoveryMultiplier,
    currentSpread,
    currentRecoilScale,
    recoilImpulse,
    moveSlide,
    createLocoState,
    stepLocomotion,
    MANTLE_RISE,
    MANTLE_MIN,
    STEP_HEIGHT,
    RELOAD_MOVE_SCALE,
    ADS_MOVE_PENALTY,
    createViewState,
    accumulateLook,
    stepLook,
    stepView,
    stepPlayer,
    LOOK_SENS,
    BREATH_TIME,
    reloadCapacity,
    makeReloadState,
    startReload,
    interruptReload,
    finishReload,
    updateReload,
    reloadBlocksFire,
    interruptShotgunReloadForFire,
    discardReloadCheckpoint,
    RELOAD_STAGE,
    isFullAuto,
    tryConsumeShot,
    fireInterval,
    SPRINT_FIRE_RAISE,
    canStartMelee,
    meleeDamage,
    beginMeleeClock,
    MELEE_RANGE,
    MELEE_DURATION,
    MELEE_BODY_DAMAGE,
    MELEE_HEAD_DAMAGE,
    rollEnemyTactic,
    enemyPlayerDamage,
    nextReactionDelay,
    nextBurstCount,
    combatSteer,
    inEnemyFov,
    patrolOffset,
    burstGap,
    ENEMY_SIGHT,
    ENEMY_HP,
    ENEMY_REACTION_MIN,
    ENEMY_REACTION_MAX,
    ENEMY_BURST_GAP,
    ENEMY_BURST_REST,
    createThrowInventory,
    canThrow,
    consumeThrow,
    addThrowables,
    spawnThrow,
    stepThrow,
    lethalEnemyDamage,
    lethalPlayerDamage,
    THROW_SPEED,
    THROW_LIFT,
    THROW_GRAVITY,
    THROW_LIFE,
    THROWABLE_MAX,
    THROWABLE_START_LETHAL,
    THROWABLE_START_TACTICAL,
    LETHAL_ENEMY_RADIUS,
    LETHAL_PLAYER_RADIUS,
    ammoLootLabel,
    weaponLootLabel,
    nearestWeaponLootIndex,
    shouldAutoPickupAmmo,
    nextAmmoCooldown,
    rollEnemyDrops,
    interactGroundWeapon,
    LOOT_WEAPON_RANGE,
    LOOT_AMMO_RANGE,
    ENEMY_DROP_WEAPON_CHANCE,
    ENEMY_DROP_WEAPON_POOL,
    AMMO_PICKUP_AMOUNT,
    AMMO_PICKUP_COOLDOWN_MS,
    crosshairCanvasSize,
    crosshairTarget,
    stepCrosshairSpread,
    adsHidesCrosshair,
    scopeBlend,
    showBreathHint,
    drawCrosshair,
    CROSSHAIR,
    createTracerFlight,
    stepTracerFlight,
    shellImpulse,
    stepShellBody,
    SPARK_LIFE,
    SHELL_LIFE,
    SHELL_GRAVITY,
    SHELL_FLOOR,
    TRACER_SPEED,
    TRACER_SPEED_SNIPER,
    TRACER_SEGMENT,
    TRACER_SEGMENT_SNIPER,
    stepDeathBody,
    deathLimbTargets,
    blendDeathLimb,
    deathGunImpulse,
    stepDeathGun,
    deathGunRestRotation,
    DEATH_DURATION,
    DEATH_GUN_DROP_AT,
    DEATH_GUN_GRAVITY,
    DEATH_GUN_FLOOR,
    damageBearing,
    damageFlashAmount,
    damageShakeAmount,
    lowHealthPulse,
    campaignStartAttachments,
    applyAttachmentMods,
    isSuppressed,
    ATTACHMENT_CATALOG,
    nameplateVisible,
    NAMEPLATE_AIM_DOT,
    NAMEPLATE_MAX_DIST,
    NAMEPLATE_HIT_REVEAL,
    sightDetectRate,
    hearSpike,
    stealthActive,
    STEALTH_FAIL_HOLD,
    createMissionState,
    zoneAt,
    infiltrationMode,
    setFlag,
    toggleNightVision,
    teachNightVision,
    interactVega,
    takeCommsModule,
    hurtVega,
    tickVegaThreat,
    triggerFuelBlast,
    triggerLightningReroute,
    spawnApcPressure,
    stepApc,
    enterZone,
    checkpointForZone,
    restoreMissionStage,
    shouldResetLivingEnemy,
    applyCheckpointRestore,
    PATH_METERS,
    SPAWN_Z,
    EXIT_Z,
    STEALTH_UNTIL_Z,
    VEGA_INTERACT_RANGE,
    MODULE_INTERACT_RANGE,
    FUEL_INTERACT_RANGE,
    VEGA_MAX_HP,
    APC_SPEED,
    ZONES,
    RADIO,
  };
})();
