// GENERATED by scripts/build.mjs from shared/movement.json — do not edit.
const SHARED_MOVEMENT = {
  "version": 1,
  "speeds": {
    "walk": 4.9,
    "sprint": 7.9,
    "crouch": 2.35,
    "prone": 1.15
  },
  "physics": {
    "acceleration": 64,
    "airAcceleration": 11,
    "friction": 11.5,
    "gravity": -19.5,
    "jumpVelocity": 6.95
  },
  "stance": {
    "standHeight": 1.72,
    "crouchHeight": 1.08,
    "proneHeight": 0.58,
    "radius": 0.36,
    "baseFov": 75
  }
};
