// GENERATED by scripts/build.mjs from shared/weapons.json — do not edit.
const SHARED_WEAPON_BASE = {
  "rifle": { id: "rifle", name: "M4 卡宾枪", magSize: 30, reserve: 210, maxReserve: 210, damage: 31, pellets: 1, rpm: 760, auto: true },
  "shotgun": { id: "shotgun", name: "KS-12 霰弹枪", magSize: 8, reserve: 48, maxReserve: 48, damage: 15, pellets: 9, rpm: 999, auto: false },
  "pistol": { id: "pistol", name: "P-9 手枪", magSize: 15, reserve: 90, maxReserve: 90, damage: 35, pellets: 1, rpm: 430, auto: false },
  "sniper": { id: "sniper", name: "SR-7 狙击枪", magSize: 5, reserve: 25, maxReserve: 25, damage: 125, pellets: 1, rpm: 999, auto: false },
  "ak": { id: "ak", name: "AK-12M 突击步枪", magSize: 30, reserve: 180, maxReserve: 240, damage: 36, pellets: 1, rpm: 680, auto: true },
  "p90": { id: "p90", name: "P90 单兵自卫武器", magSize: 50, reserve: 200, maxReserve: 250, damage: 24, pellets: 1, rpm: 900, auto: true },
};
